### ISSUE TITLE
Make HCIGETDEVINFO available at Javascript level

### ISSUE THREAD

**Issue by george-hawkins** [sandeepmistry/bleno#101]
In noble when I discover a _remote_ device I can print its address etc.

However in neither bleno nor noble can I print the address of the _local_ adapter.

This information is retrieved in the [`HCIGETDEVINFO` call](https://github.com/sandeepmistry/bleno/blob/58013b1ea3e30808cdaa892b14f6cc673ba8d0bd/src/hci-ble.c#L179) in `hci-ble.c` but it's not made available at the Javascript level.

It would be nice if address and maybe some of the other fields in `hci_dev_info` were visible.

PS bleno and noble are absolutely super. Definitely the easiest way into working with BLE. Thanks :)

**Comment by sandeepmistry** [comment]
@george-hawkins good suggestion, I've implemented the address so far on the Linux side in: https://github.com/sandeepmistry/bleno/commit/5760aaf19161df20374dd395b1f14b09a22c6fd2

You can access the address via ``bleno.address``, it is set to ``unknown`` prior to a state change (and on OS X).


I don't know how useful the other fields are, so left them out for now ...
