### ISSUE TITLE
Understanding how this works...

### ISSUE THREAD

**Issue by gkodikara** [sandeepmistry/bleno#113]
Hi there -

Could someone give me an idea of how this works? I'm trying to mimic setup of a beacon but even running the examples I'm not getting my head around how this can be achieved.

Appreciate any help.

Greg

**Comment by sandeepmistry** [comment]
@gkodikara the examples are not beacon related, you'll need a bit of knowledge of BLE to get going.

For iBeacon please see read me for API's or the ```node-bleacon``` module.
