### ISSUE TITLE
stopAdvertising not calling callback

### ISSUE THREAD

**Issue by carlonluca** [sandeepmistry/bleno#122]
When trying to stopAdvertising I don't seem to be getting any callback. This is what I'm using to terminate in the advertisingStart callback:

```
log.info("Stopping...");
bleno.stopAdvertising(function() {
   log.info("Bye bye ;-)");
});
```

Tried to place this also somewhere else but no callback. Any idea why?

**Comment by sandeepmistry** [comment]
@carlonluca thanks for reporting. I've fixed with https://github.com/sandeepmistry/bleno/commit/a9cb6feceb03c5862b990b09cf633a9c4e9466c2, and published version 0.2.1 with the fix.
