### ISSUE TITLE
Advertising power

### ISSUE THREAD

**Issue by carlonluca** [sandeepmistry/bleno#125]
I see BLENO_ADVERTISING_INTERVAL can be used to set the frequency of the advertising packets. I tried that and it works perfectly. But is it possible also to set the tx power of the advertising by any chance? Is there a way to do it? What is the default power?

**Comment by sandeepmistry** [comment]
@carlonluca nothing yet, a pull request would be great :)

Default power is whatever the adapter defaults to. Which I think is ```sudo hciconfig hci0 inqtpl```, but not 100% sure.

**Comment by carlonluca** [comment]
Yes, I found that too. Although trying to modify it had no result. I'll investigate further. Thanks for answering.

**Comment by sandeepmistry** [comment]
Yes, I had a similar observation here: https://github.com/don/node-eddystone-beacon/issues/19

**Comment by carlonluca** [comment]
Oh, it means I'm not alone... :-) maybe not possible to do that with the hardware... it may be confirmed if there was a way to get the range of available values but I couldn't find it.

**Comment by sandeepmistry** [comment]
@carlonluca any progress or should I close?

**Comment by carlonluca** [comment]
It depends on you.

**Comment by sandeepmistry** [comment]
Closing this for now, since we haven't been able to find a HCI command to set the TX power level.
