### ISSUE TITLE
MAC from connecting device is different

### ISSUE THREAD

**Issue by danki** [sandeepmistry/bleno#130]
From time to time, the connecting device mac address in bleno on accept, is changing.

Here's a little output:
+ Accepting connection from: 78:7C:53:A4:DD:6C
+ Previous addresses: 
a1) 44:E2:B3:92:DE:70 
a2) 5A:18:BA:01:8C:CA
a3) 76:CA:73:95:BA:22 
a4) 78:7C:53:A4:DD:6C

When looking at the mac address on my phone (the device that connects to bleno) none of the adresses above match my BT MAC on phone.
On my Phone it ends with: ...:21:64

Why is bleno getting a completely different from the phone ?

Im running bleno on Intel Edison, if that helps

**Comment by sandeepmistry** [comment]
@danki this is expected, iOS uses a random rotating BT address for privacy reasons - nothing bleno can do about this.
