### ISSUE TITLE
Is osx (yosemite) able to change device name?

### ISSUE THREAD

**Issue by jacobrosenthal** [sandeepmistry/bleno#132]
Docs seem to say you can, but have to
```
sudo BLENO_DEVICE_NAME="Battery" node examples/battery-service/main.js 
```
But that doesn't appear to work for me.

**Comment by sandeepmistry** [comment]
@jacobrosenthal that's in the Linux only section right? Do you see it elsewhere?

https://github.com/sandeepmistry/bleno#running-on-linux

**Comment by jacobrosenthal** [comment]
True enough

**Comment by sandeepmistry** [comment]
You might be able to change it non-programmatically via: OS X Settings -> Sharing -> Computer Name
