### ISSUE TITLE
Battery Service on OSX (Yosemite) broken?

### ISSUE THREAD

**Issue by jacobrosenthal** [sandeepmistry/bleno#133]
On linux I appear to have a connectable battery service, but not in yosemite.
![img_2332](https://cloud.githubusercontent.com/assets/455796/10149895/c1a099fc-663c-11e5-98e7-a504a3d52368.PNG)
![img_2333](https://cloud.githubusercontent.com/assets/455796/10149896/c1a243f6-663c-11e5-81c4-9e82ff5a3706.PNG)

**Comment by jacobrosenthal** [comment]
[osx log](https://gist.github.com/jacobrosenthal/0cff7544c46346573e56)
[linux log](https://gist.github.com/jacobrosenthal/b6ab2205da5bad6ad0f5)

**Comment by jacobrosenthal** [comment]
Aha, https://gist.github.com/jacobrosenthal/0cff7544c46346573e56#file-gistfile1-txt-L101 is an error, but the example doesnt catch it. (think il PR that)

[Error: failed to set service 180F, UUID not allowed!]

**Comment by sandeepmistry** [comment]
@jacobrosenthal unfortunately OS X 10.10 stopped allowing that UUID. It used to work in 10.9, then they blocked it along with some other UUID's.

Does bleno report an error on ```setServices``` callback?

**Comment by jacobrosenthal** [comment]
Yes, The error comes through, the example just doesnt catch it. Probably for brevity's sake. So just PR a note on battery example that it doesnt work on osx starting at 10.10?

**Comment by jacobrosenthal** [comment]
Do you have a link to anything with those UUIDs? A simple search hasnt pulled them up yet

**Comment by sandeepmistry** [comment]
@jacobrosenthal Apple docs a very vague: https://developer.apple.com/library/mac/documentation/CoreBluetooth/Reference/CoreBluetooth_Constants/index.html#//apple_ref/c/tdef/CBError

```
CBErrorUUIDNotAllowed
The specified UUID is not permitted.

Available in OS X v10.9 and later.
```

**Comment by sandeepmistry** [comment]
> Yes, The error comes through, the example just doesnt catch it. Probably for brevity's sake. So just PR a note on battery example that it doesnt work on osx starting at 10.10?

That would be great!

The error should be reported in main.js, with something like this:

```javascript
// ...

bleno.on('servicesSet', function(error) {
    console.log(error);
});
```

**Comment by jacobrosenthal** [comment]
Do you want to pollute the example with the error logic? I assumed it was
left off brevity.

**Comment by jacobrosenthal** [comment]
Wow. CBErrorUUIDNotAllowed doesnt even google really. A huge amount of peripherals have a battery as mandatory.. Can you even properly create those without a battery service?

**Comment by jacobrosenthal** [comment]
Ran through the current list on bluetooth sig. Heres the ones that error.
180F Battery
1812 Human Interface Device
1805 Current Time Service
180A Device Information
1800 Generic Access
1801 Generic Attribute

**Comment by sandeepmistry** [comment]
From the [CBMutableService](https://developer.apple.com/library/mac/documentation/CoreBluetooth/Reference/CBMutableService_Class/index.html#//apple_ref/occ/instm/CBMutableService/initWithType:primary:) docs, only 128-bit UUIDS should be used:

```
UUID	
A 128-bit UUID that identifies the service.
```

However, if I try 0xffff with bleno it's fine ...
