### ISSUE TITLE
Disable `bluetoothd` instructions

### ISSUE THREAD

**Issue by bradfol** [sandeepmistry/bleno#150]
Can you provide more instructions on how to disable `bluetoothd` according to this line:
https://github.com/sandeepmistry/bleno/commit/ef572ec86e8790e5f8fa8cd00d197cd9b0a2b72b#diff-04c6e90faac2675aa89e2176d2eec7d8R23

I am experiencing many issues with my project after upgrading to Debian Jessie on a Raspberry Pi. Want to make sure that the installation and environment are set up correctly.

**Comment by sandeepmistry** [comment]
@bradfol I've added some notes in https://github.com/sandeepmistry/bleno/commit/9ee47c43cc961032a6897568504a3d0b07869f7a
