### ISSUE TITLE
Support for Physical Web beacons?

### ISSUE THREAD

**Issue by kenchris** [sandeepmistry/bleno#152]
I would really like support for physical web beacons:

https://google.github.io/physical-web/
http://arstechnica.com/gadgets/2015/07/meet-googles-eddystone-a-flexible-open-source-ibeacon-fighter/
https://developers.google.com/beacons/

**Comment by ragingwind** [comment]
@kenchris You can use eddystone-beacon for it. It is based also based on  https://www.npmjs.com/package/eddystone-beacon

**Comment by sandeepmistry** [comment]
@kenchris yes, please see the node-eddystone-beacon project @ragingwind suggested, it is built on top of bleno:

https://github.com/don/node-eddystone-beacon
