### ISSUE TITLE
Changing MAC Adress

### ISSUE THREAD

**Issue by paulgavrikov** [sandeepmistry/bleno#153]
Is there a way to change the MAC adress that is broadcasted from a peripherial?

**Comment by sandeepmistry** [comment]
@paulgavrikov this is not implemented currently.

Could you please provide more details on your use case?

**Comment by paulgavrikov** [comment]
I am working on a repeater device, which works by mirroring a peripheral. I know that some chinese devices support changing MAC, so I was wondering if this could work here, too.

**Comment by sandeepmistry** [comment]
@paulgavrikov bleno could support using a random BT address on Linux, but not a high priority currently.

For public address, you can use the BlueZ ```bdaddr``` tool can be used to change the address of most CSR and Broadcom adapters.

http://git.kernel.org/cgit/bluetooth/bluez.git/tree/tools/bdaddr.c

**Comment by paulgavrikov** [comment]
Thanks! I will try bdaddr!

**Comment by sandeepmistry** [comment]
@paulgavrikov no problem!
