### ISSUE TITLE
[Beginners] Set characteristic value

### ISSUE THREAD

**Issue by ducmaxime** [sandeepmistry/bleno#162]
Hello,

I have two characteristics (example: charact1, charact2) on my Gatt service.

I want set value of charact2 when my client set the value of charact1.

Can you help me ?

**Comment by sandeepmistry** [comment]
@ducmaxime what have you tried so far?

**Comment by ducmaxime** [comment]
I have find a solution. Thank you.

**Comment by sandeepmistry** [comment]
@ducmaxime care you share what you did, so others can use it as a reference?
