### ISSUE TITLE
bleno, noble can control multiple dongle?

### ISSUE THREAD

**Issue by seong889** [sandeepmistry/bleno#163]
I want to control several Bluetooth dongles in one of the RPI2.
The document contains a device that can be selected via the 'BLENO_HCI_DEVICE_ID' option.
Is it possible to control several devices through the options like this?

**Comment by sandeepmistry** [comment]
@seong889 yes, but you have to launch a separate Node.js process per adapter.

**Comment by seong889** [comment]
so, I can't control several adapters on one of Node.js process???

**Comment by sandeepmistry** [comment]
> so, I can't control several adapters on one of Node.js process???

With the bleno code as is, this is correct.

However, if you dive in an fork bleno, I'm sure you can change it to get it working.
