### ISSUE TITLE
Android client Characteristic name is always "Unknown"

### ISSUE THREAD

**Issue by ducmaxime** [sandeepmistry/bleno#166]
Hello, how can I set the characteristic name ?

My function  : 

var GetConfiguration = function()
{
    GetConfiguration.super_.call(this,
    {
        uuid:       '31E98556-045A-4A22-9E88-6BF944352C21',
        properties: ['read', 'write', 'indicate'],
        value:      null
    });

    this._value                 = new Buffer(0);
    this._updateValueCallback   = null;
};
In my android client I receive "Unknown" for the characteristic name :
<img width="1075" alt="screen shot 2016-01-18 at 10 28 47" src="https://cloud.githubusercontent.com/assets/6499846/12387655/65f55a04-bdce-11e5-926b-438e3b8f837d.png">

Thanks,

**Comment by nickhod** [comment]
I also would like to know how to set the name of both Characteristics and Services.

Thanks.

**Comment by sandeepmistry** [comment]
@ducmaxime this might not be possible on Android, the name might only be set for Bluetooth SIG standard UUID's:

 * https://developer.bluetooth.org/gatt/services/Pages/ServicesHome.aspx?_ga=1.44626528.591292021.1365037697
 * https://developer.bluetooth.org/gatt/characteristics/Pages/CharacteristicsHome.aspx?_ga=1.44626528.591292021.1365037697

You could trying adding a [user description descriptor](https://developer.bluetooth.org/gatt/descriptors/Pages/DescriptorViewer.aspx?u=org.bluetooth.descriptor.gatt.characteristic_user_description.xml) to the characteristic, see:

https://github.com/sandeepmistry/bleno/blob/master/test.js#L17-L21

@don do you have any info on this?

**Comment by sandeepmistry** [comment]
I'm closing this, as nothing can be done the bleno side.
