### ISSUE TITLE
Creating secondary services?

### ISSUE THREAD

**Issue by dfowler7437** [sandeepmistry/bleno#168]
What is the "setServices" method used for?  I'd assume to set services under the primary service which are "discovered" after connection. I don't seen enough documentation to make this clear for me.  How do we add services under the primary?

If I read iOS and BT documentation correctly, you can have a primary service with a full UUID then have "services for a service" under that service with full UUIDs. if that's true, how with bleno?

**Comment by sandeepmistry** [comment]
@dfowler7437 I've clarified the ```setServices``` API in https://github.com/sandeepmistry/bleno/commit/bc266dc30e5b4c62b2db0a15fb0e9fdebd654edf.

There is no support for adding secondary services, however there was some discussions on adding secondary services in #88, however is what not supported by OS X at that time. At this time I do not see much value for support secondary services.
