### ISSUE TITLE
Unable to scan bleno example files with gatttool.

### ISSUE THREAD

**Issue by Dan-Azure** [sandeepmistry/bleno#172]
Maybe I'm doing it wrong?

I took the echo example js files, changed the "require" in them to point to the bleno install.
Then on a separate device I installed Bluez-5.37

So this is two Edisons talking to each other. The Slave (running the echo service with Bleno) gives me

\> HCI Event: LE Meta Event (0x3e) plen 19
    LE Connection Complete
      status 0x00 handle 64, role slave
      bdaddr <snip> (Public)
\> ACL data: handle 64 flags 0x02 dlen 9
    ATT: Find Information req (0x04)
      start 0x0001, end 0xffff
< ACL data: handle 64 flags 0x00 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0001, uuid 0x2800 (GATT Primary Service)
        handle 0x0004, uuid 0x2803 (GATT Characteristic)
        handle 0x0006, uuid 0x2a00 (GATT(type) Device Name)
        handle 0x0007, uuid 0x2803 (GATT Characteristic)
        handle 0x0008, uuid 0x2a01 (GATT(type) Appearance)
< ACL data: handle 64 flags 0x00 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0001, uuid 0x2800 (GATT Primary Service)
        handle 0x0002, uuid 0x2803 (GATT Characteristic)
        handle 0x0003, uuid 0x2a00 (GATT(type) Device Name)
        handle 0x0004, uuid 0x2803 (GATT Characteristic)
        handle 0x0005, uuid 0x2a01 (GATT(type) Appearance)
\> ACL data: handle 64 flags 0x02 dlen 9
    ATT: Find Information req (0x04)
      start 0x0009, end 0xffff
\> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 64 packets 2
< ACL data: handle 64 flags 0x00 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0009, uuid 0x2902 (GATT(desc) Client Characteristic Configuration)
        handle 0x000a, uuid 0x2800 (GATT Primary Service)
        handle 0x000b, uuid 0x2803 (GATT Characteristic)
        handle 0x000c, uuid 0xec0e (Unknown)
        handle 0x000d, uuid 0x2902 (GATT(desc) Client Characteristic Configuration)
\> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 64 packets 1
< ACL data: handle 64 flags 0x00 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0009, uuid 0x2800 (GATT Primary Service)
        handle 0x000a, uuid 0x2803 (GATT Characteristic)
        handle 0x000b, uuid 0x2a06 (Unknown)
        handle 0x000c, uuid 0x2800 (GATT Primary Service)
        handle 0x000d, uuid 0x2803 (GATT Characteristic)
\> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 64 packets 1
\> HCI Event: Disconn Complete (0x05) plen 4
    status 0x00 handle 64 reason 0x13
    Reason: Remote User Terminated Connection
< HCI Command: LE Set Advertise Enable (0x08|0x000a) plen 1
  0000: 01                                                .
\> HCI Event: Command Complete (0x0e) plen 4
    LE Set Advertise Enable (0x08|0x000a) ncmd 1
    status 0x00

I don't know, this all looks sensible to me. On the Master, I get:

root@edison:~/bluez-5.37/attrib# ./gatttool -b <snip> --char-desc
< HCI Command: LE Create Connection (0x08|0x000d) plen 25
    bdaddr <snip> type 0
    interval 96 window 48 initiator_filter 0
    own_bdaddr_type 0 min_interval 40 max_interval 56
    latency 0 supervision_to 42 min_ce 0 max_ce 0
\> HCI Event: Command Status (0x0f) plen 4
    LE Create Connection (0x08|0x000d) status 0x00 ncmd 1
\> HCI Event: LE Meta Event (0x3e) plen 19
    LE Connection Complete
      status 0x00 handle 64, role master
      bdaddr <snip> (Public)
< ACL data: handle 64 flags 0x00 dlen 9
    ATT: Find Information req (0x04)
      start 0x0001, end 0xffff
\> ACL data: handle 64 flags 0x02 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0001, uuid 0x2800 (GATT Primary Service)
        handle 0x0004, uuid 0x2803 (GATT Characteristic)
        handle 0x0006, uuid 0x2a00 (GATT(type) Device Name)
        handle 0x0007, uuid 0x2803 (GATT Characteristic)
        handle 0x0008, uuid 0x2a01 (GATT(type) Appearance)
< ACL data: handle 64 flags 0x00 dlen 9
    ATT: Find Information req (0x04)
      start 0x0009, end 0xffff
\> ACL data: handle 64 flags 0x02 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0001, uuid 0x2800 (GATT Primary Service)
        handle 0x0002, uuid 0x2803 (GATT Characteristic)
        handle 0x0003, uuid 0x2a00 (GATT(type) Device Name)
        handle 0x0004, uuid 0x2803 (GATT Characteristic)
        handle 0x0005, uuid 0x2a01 (GATT(type) Appearance)
Discover descriptors failed: Request attribute has encountered an unlikely error
\> HCI Event: Number of Completed Packets (0x13) plen 5
    handle 64 packets 2
\> ACL data: handle 64 flags 0x02 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0009, uuid 0x2902 (GATT(desc) Client Characteristic Configuration)
        handle 0x000a, uuid 0x2800 (GATT Primary Service)
        handle 0x000b, uuid 0x2803 (GATT Characteristic)
        handle 0x000c, uuid 0xec0e (Unknown)
        handle 0x000d, uuid 0x2902 (GATT(desc) Client Characteristic Configuration)
\> ACL data: handle 64 flags 0x02 dlen 26
    ATT: Find Information resp (0x05)
      format: uuid-16
        handle 0x0009, uuid 0x2800 (GATT Primary Service)
        handle 0x000a, uuid 0x2803 (GATT Characteristic)
        handle 0x000b, uuid 0x2a06 (Unknown)
        handle 0x000c, uuid 0x2800 (GATT Primary Service)
        handle 0x000d, uuid 0x2803 (GATT Characteristic)
< HCI Command: Disconnect (0x01|0x0006) plen 3
    handle 64 reason 0x13
    Reason: Remote User Terminated Connection
\> HCI Event: Command Status (0x0f) plen 4
    Disconnect (0x01|0x0006) status 0x00 ncmd 1
\> HCI Event: Disconn Complete (0x05) plen 4
    status 0x00 handle 64 reason 0x16
    Reason: Connection Terminated by Local Host

whereupon the gatttool call hangs.

**Comment by sandeepmistry** [comment]
@Dan-Azure it looks like you have a version of BlueZ 5.x bluetoothd running at the same time.

Please see the read me about how to disable: 

 * https://github.com/sandeepmistry/bleno#linux
 * http://rexstjohn.com/configure-intel-edison-for-bluetooth-le-smart-development/
