### ISSUE TITLE
Continuous PoweredOff state on OSX

### ISSUE THREAD

**Issue by shekit** [sandeepmistry/bleno#173]
Hi,

I have a 2011 macbook pro(OSX 10.11.1) and I am using a BLE dongle with it. I've ensured the dongle is selected as the default bluetooth device using the Xcode Hardware IO Tools and I am trying to make my macbook pro be a peripheral. 

However on 'stateChange' is continuously showing a state of 'poweredOff' and as such it is not advertising anything. It is not showing up in LightBlue either.

Here is my code : https://github.com/shekit/peeqo-robot/blob/master/bleno_test/index.js

Since the exact same code seems to be working on the raspberry pi, I'm unsure where the issue lies.

**Comment by sandeepmistry** [comment]
@shekit I suspect this is something to do with your setup.

Please see if the LightBlue OS X app or a native CoreBluetooth app has the same issue. If not, please re-open this issue.

Here's a sample native CoreBluetooth app: https://github.com/sandeepmistry/osx-ble-peripheral
