### ISSUE TITLE
UUID of primary service cannot be changed

### ISSUE THREAD

**Issue by azukileaf** [sandeepmistry/bleno#174]
Hello.

I'm using bleno in Raspberry Pi 2, and I connect it from android.
The UUID of primary service cannot be changed.

For example, I tried echo example of bleno, the UUID of primary service cannot be changed from 0000ec00-0000-1000-8000-00805f9b34fb (ec00), even if I changed the UUID part (ex. ec01).
The advertising UUID can be changed, so onScanResult() of BluetoothLeScanner returns the changed UUID (ec01).
But getServices() returns the former UUID (ec00).

This problem is not resolved even if I re-up the hci0, restart OS, re-plug the Bluetooth adapter (USB), reset from hcitool.
If a new Bluetooth adapter is plugged, the UUID can be changed for the first time only.
My Bluez version is 4.99, but same problem in 5.37. Node version is 5.5.0.
The Bluetooth adapter and the android phone can use Bluetooth 4.0.

Maybe I'm making an elementary mistake.
Thank you for responding.

**Comment by sandeepmistry** [comment]
@azukileaf make sure you've change both the advertising UUID and service UUID:

 * https://github.com/sandeepmistry/bleno/blob/master/examples/echo/main.js#L13
 * https://github.com/sandeepmistry/bleno/blob/master/examples/echo/main.js#L25
