### ISSUE TITLE
Mac Blued XPC

### ISSUE THREAD

**Issue by TorstenRobitzki** [sandeepmistry/bleno#177]
Hi,
I still try to use bleno to execute a GATT "Discover Primary Service by Service UUID" sub procedure. I had a look at the Mac implementation and as far as I understand it, it directly communicate with the blued daemon. Do you get the messages ids by "reverse" engineering, or is there some kind of documentation available?

thanks in advance for your assistance,
Torsten

**Comment by sandeepmistry** [comment]
@TorstenRobitzki 

> Do you get the messages ids by "reverse" engineering, or is there some kind of documentation available?

Reverse engineering, please see https://github.com/sandeepmistry/osx-ble-peripheral/blob/add-remove-services/BLEPeripheral/BPAppDelegate.m. Method swizzling is used to spy on the XPC messages CoreBluetooth uses.
