### ISSUE TITLE
Please describe what exactly to do to run bleno and noble?

### ISSUE THREAD

**Issue by mihir-harbinger** [sandeepmistry/bleno#178]
I could not understand how to install bleno and noble and work with them. I don't have rpi or arduino boards. I just have my Mac and nexus 6. How do I run these two apps using Mac and nexus. Forgive my naïvety. Thanks in advance. I have fair knowledge of NodeJS. Please let me know as soon as possible.

**Comment by sandeepmistry** [comment]
Closing, discussion continued on gitter.
