### ISSUE TITLE
Bleno doesn't work on Brillo (Linux and Android based IoT OS)

### ISSUE THREAD

**Issue by kenchris** [sandeepmistry/bleno#182]
Changing this line 

```} else if (platform === 'linux') {```

to

```} else if (platform === 'linux' || platform === 'android') {```

and it works fine.

**Comment by sandeepmistry** [comment]
@kenchris thanks for the heads up.

To confirm does only [this](https://github.com/sandeepmistry/bleno/blob/master/lib/bleno.js#L19) line need to change or also the [``os`` section in ``package.json``](https://github.com/sandeepmistry/bleno/blob/master/package.json#L9-L13)?

It would be great if you could submit a pull request ...

**Comment by poussa** [comment]
I think we can live with the code change only but it would be better to have it also on .json file.

**Comment by sandeepmistry** [comment]
Closed via #195.
