### ISSUE TITLE
Not working on RPi3

### ISSUE THREAD

**Issue by shekit** [sandeepmistry/bleno#193]
Hi,

I'm unable to install bleno on raspbian jessie on a pi3. I keep a bunch of errors during installation as it seems to want node version >0.12 but the current version on jessie is 0.10.29. This version seems to be the latest version and I cannot seem to upgrade it. I have node running on my path correctly as well.

**Comment by WayneKeenan** [comment]
have a look at the NodeJS section of this: https://github.com/TheBubbleWorks/TheBubbleWorks_RaspberryPi_BLE_GPIO_Server/blob/master/INSTALL.md

**Comment by sandeepmistry** [comment]
@shekit it's hard to help unless you share the output of the installation errors :)

**Comment by shekit** [comment]
Hi @sandeepmistry I'm going to try @WayneKeenan's suggestion and report back. I think it might just be the case of updating the node version to the latest 5.x as suggested in the link

**Comment by sandeepmistry** [comment]
Ok, I'll close for now then.
