### ISSUE TITLE
Connected devices get disconnected after 2 seconds

### ISSUE THREAD

**Issue by LuckySeven** [sandeepmistry/bleno#196]
Hi all, i was using bleno on Raspberry Pi2 without problems.
Now i'm working on Pi3 but there's a problem: after 2 or 3 seconds, the connected device gets disconnected, so i can't do any operations.

Is this a library issue or i should change something on bluetooth config files?

Update:
i'm using Bluez 5.23. Should i downgrade to older version?

**Comment by sandeepmistry** [comment]
This sounds similar to #180.

Please make sure you are using ```bluetooth-hci-socket``` v0.4.3 (via `npm ls`). As well as stopping bluetoothd if you are running BlueZ 5.x or higher: https://github.com/sandeepmistry/bleno#linux

Let me know if doing the above does not fix things.
