### ISSUE TITLE
WithEIRData on ODROID/Ubuntu

### ISSUE THREAD

**Issue by sdebruin** [sandeepmistry/bleno#202]
I am attempting to use the startAdvertisingWithEIRData function to append additional information to my advertisement or scan response packets. I am currently just trying to verify functionality by stuffing dummy data into the advertisementData:

Simplified from my code:
`var advertisementData = new Buffer("02FFAA", "hex");`
`bleno.startAdvertisingWithEIRData(advertisementData);`

I am attempting to read the packet via Android on the nRF Master Control Panel, but it seems as if I am not getting the data through correctly. On the raw packet viewer, there are still just the three types (0x01, 0x0A for txPwr, and 0x09 for the name). My data is not coming through. 

The bleno-running device is an ODROID running Ubuntu, is there anything obvious that I am doing wrong? Thank you.

**Comment by sandeepmistry** [comment]
@sdebruin I would definitely recommend adding EIR flags type to the advertisement: `020106`.

Maybe you could also try the `isYocto` workaround, by setting the `isYocto` var to `true` in [lib/hci-socket/gap.js](https://github.com/sandeepmistry/bleno/blob/master/lib/hci-socket/gap.js#L11).
