### ISSUE TITLE
Broadcasting property

### ISSUE THREAD

**Issue by Mesaman** [sandeepmistry/bleno#204]
Is it possible to implement a broadcasting property for the characteristics?

**Comment by sandeepmistry** [comment]
Hi @Mesaman,

This is not supported at this moment. However, you can use `bleno.startAdvertisingWithEIRData(...)` to specify the advertisement data that contained service data. [node-eddystone-beacon](https://github.com/don/node-eddystone-beacon) has a good example of this.

https://github.com/sandeepmistry/bleno#start-advertising-with-eir-data-linux-only
