### ISSUE TITLE
Can't run on multiple adapters

### ISSUE THREAD

**Issue by mhoresh** [sandeepmistry/bleno#206]
I tried to run two instances of node, each of which implementing the same service, one on hci0 and the other on hci1 (using the BLENO_HCI_DEVICE_ID environment variable) . Only one of the services worked properly. the other one stopped advertising.

**Comment by rodrigosalinas** [comment]
I have the very same problem in Ubuntu 15.04 and Node 6.

**Comment by sandeepmistry** [comment]
@mhoresh @rodrigosalinas please provide debug lots:

```
sudo DEBUG=* BLENO_HCI_DEVICE_ID=0 <file>.js
sudo DEBUG=* BLENO_HCI_DEVICE_ID=1 <file>.js
```

Also, have you stopped bluetoothd if you are using BlueZ 5.x?

**Comment by mhoresh** [comment]
I am using BlueZ 5.x and have stopped the bluetooth service. 

This is the log from HCI1:
  gatt handles = [
  {},
  {
    "type": "service",
    "uuid": "1800",
    "startHandle": 1,
    "endHandle": 5
  },
  {
    "type": "characteristic",
    "uuid": "2a00",
    "properties": 2,
    "secure": 0,
    "startHandle": 2,
    "valueHandle": 3
  },
  {
    "type": "characteristicValue",
    "handle": 3,
    "value": "Buffer('77732d6d6f727269732d7562756e7475', 'hex')"
  },
  {
    "type": "characteristic",
    "uuid": "2a01",
    "properties": 2,
    "secure": 0,
    "startHandle": 4,
    "valueHandle": 5
  },
  {
    "type": "characteristicValue",
    "handle": 5,
    "value": "Buffer('8000', 'hex')"
  },
  {
    "type": "service",
    "uuid": "1801",
    "startHandle": 6,
    "endHandle": 9
  },
  {
    "type": "characteristic",
    "uuid": "2a05",
    "properties": 32,
    "secure": 0,
    "startHandle": 7,
    "valueHandle": 8
  },
  {
    "type": "characteristicValue",
    "handle": 8,
    "value": "Buffer('00000000', 'hex')"
  },
  {
    "type": "descriptor",
    "handle": 9,
    "uuid": "2902",
    "properties": 14,
    "secure": 0,
    "value": "Buffer('0000', 'hex')"
  }
] +0ms
  bleno platform linux +5ms
  hci setting filter to: 1400000020c10000000000400000 +3ms
  hci set event mask - writing: 01010c08fffffbff07f8bf3d +0ms
  hci set le event mask - writing: 010120081f00000000000000 +1ms
  hci read local version - writing: 01011000 +0ms
  hci write LE host supported - writing: 016d0c020100 +0ms
  hci read LE host supported - writing: 016c0c00 +0ms
  hci read bd addr - writing: 01091000 +0ms
  hci onSocketData: 040e0401010c00 +11ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 3073 +0ms
  hci 		status = 0 +1ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401012000 +0ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8193 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0c0101100006bb22060a00bb22 +4ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 4097 +0ms
  hci 		status = 0 +0ms
  hci 		result = 06bb22060a00bb22 +0ms
  hci set advertise enable - writing: 010a200100 +0ms
  hci set advertisement parameters - writing: 0106200fa000a0000000000000000000000700 +1ms
  hci onSocketData: 040e04016d0c00 +0ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 3181 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e06016c0c000100 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 3180 +0ms
  hci 		status = 0 +0ms
  hci 		result = 0100 +0ms
  hci 			le = 1 +0ms
  hci 			simul = 0 +0ms
  hci onSocketData: 040e0a010910000871da7d1a00 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 4105 +0ms
  hci 		status = 0 +0ms
  hci 		result = 0871da7d1a00 +0ms
  hci address = 00:1a:7d:da:71:08 +1ms
  bleno addressChange 00:1a:7d:da:71:08 +0ms
  hci onSocketData: 040e04010a200c +0ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8202 +0ms
  hci 		status = 12 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401062000 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8198 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  bleno stateChange poweredOn +0ms
on -> stateChange: poweredOn
  gap startAdvertising: name = PM-HR-MONITOR-1, serviceUuids = [
  "180D"
] +5ms
  gap startAdvertisingWithEIRData: advertisement data = 02010603030d18, scan data = 1008504d2d48522d4d4f4e49544f522d31 +1ms
  hci set scan response data - writing: 01092020111008504d2d48522d4d4f4e49544f522d310000000000000000000000000000 +0ms
  hci set advertisement data - writing: 010820200702010603030d18000000000000000000000000000000000000000000000000 +0ms
  hci set advertise enable - writing: 010a200101 +0ms
  hci set scan response data - writing: 01092020111008504d2d48522d4d4f4e49544f522d310000000000000000000000000000 +0ms
  hci set advertisement data - writing: 010820200702010603030d18000000000000000000000000000000000000000000000000 +0ms
  hci onSocketData: 040e0401092000 +4ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8201 +1ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401082000 +0ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8200 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e04010a2000 +0ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8202 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  bleno advertisingStart: null +0ms
on -> advertisingStart: success
  gatt handles = [
  {},
  {
    "type": "service",
    "uuid": "1800",
    "startHandle": 1,
    "endHandle": 5
  },
  {
    "type": "characteristic",
    "uuid": "2a00",
    "properties": 2,
    "secure": 0,
    "startHandle": 2,
    "valueHandle": 3
  },
  {
    "type": "characteristicValue",
    "handle": 3,
    "value": "Buffer('77732d6d6f727269732d7562756e7475', 'hex')"
  },
  {
    "type": "characteristic",
    "uuid": "2a01",
    "properties": 2,
    "secure": 0,
    "startHandle": 4,
    "valueHandle": 5
  },
  {
    "type": "characteristicValue",
    "handle": 5,
    "value": "Buffer('8000', 'hex')"
  },
  {
    "type": "service",
    "uuid": "1801",
    "startHandle": 6,
    "endHandle": 9
  },
  {
    "type": "characteristic",
    "uuid": "2a05",
    "properties": 32,
    "secure": 0,
    "startHandle": 7,
    "valueHandle": 8
  },
  {
    "type": "characteristicValue",
    "handle": 8,
    "value": "Buffer('00000000', 'hex')"
  },
  {
    "type": "descriptor",
    "handle": 9,
    "uuid": "2902",
    "properties": 14,
    "secure": 0,
    "value": "Buffer('0000', 'hex')"
  },
  {
    "type": "service",
    "uuid": "180D",
    "startHandle": 10,
    "endHandle": 17
  },
  {
    "type": "characteristic",
    "uuid": "2A37",
    "properties": 16,
    "secure": 0,
    "startHandle": 11,
    "valueHandle": 12
  },
  {
    "type": "characteristicValue",
    "handle": 12,
    "value": null
  },
  {
    "type": "descriptor",
    "handle": 13,
    "uuid": "2902",
    "properties": 14,
    "secure": 0,
    "value": "Buffer('0000', 'hex')"
  },
  {
    "type": "descriptor",
    "handle": 14,
    "uuid": "2901",
    "properties": 2,
    "secure": 0,
    "value": "Heart rate"
  },
  {
    "type": "characteristic",
    "uuid": "2A38",
    "properties": 2,
    "secure": 0,
    "startHandle": 15,
    "valueHandle": 16
  },
  {
    "type": "characteristicValue",
    "handle": 16,
    "value": null
  },
  {
    "type": "descriptor",
    "handle": 17,
    "uuid": "2901",
    "properties": 2,
    "secure": 0,
    "value": "Sensor location"
  }
] +1ms
  bleno servicesSet +1ms
setServices: success
  hci onSocketData: 040e0401092000 +3ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8201 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401082000 +4ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8200 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  mgmt on data ->0b0000000d00dc6c0088867b02000000000000 +4s
  mgmt on data ->0c0000000800dc6c0088867b0203 +4s



This is the log from HCI0:
  gatt handles = [
  {},
  {
    "type": "service",
    "uuid": "1800",
    "startHandle": 1,
    "endHandle": 5
  },
  {
    "type": "characteristic",
    "uuid": "2a00",
    "properties": 2,
    "secure": 0,
    "startHandle": 2,
    "valueHandle": 3
  },
  {
    "type": "characteristicValue",
    "handle": 3,
    "value": "Buffer('77732d6d6f727269732d7562756e7475', 'hex')"
  },
  {
    "type": "characteristic",
    "uuid": "2a01",
    "properties": 2,
    "secure": 0,
    "startHandle": 4,
    "valueHandle": 5
  },
  {
    "type": "characteristicValue",
    "handle": 5,
    "value": "Buffer('8000', 'hex')"
  },
  {
    "type": "service",
    "uuid": "1801",
    "startHandle": 6,
    "endHandle": 9
  },
  {
    "type": "characteristic",
    "uuid": "2a05",
    "properties": 32,
    "secure": 0,
    "startHandle": 7,
    "valueHandle": 8
  },
  {
    "type": "characteristicValue",
    "handle": 8,
    "value": "Buffer('00000000', 'hex')"
  },
  {
    "type": "descriptor",
    "handle": 9,
    "uuid": "2902",
    "properties": 14,
    "secure": 0,
    "value": "Buffer('0000', 'hex')"
  }
] +0ms
  bleno platform linux +6ms
  hci setting filter to: 1400000020c10000000000400000 +2ms
  hci set event mask - writing: 01010c08fffffbff07f8bf3d +1ms
  hci set le event mask - writing: 010120081f00000000000000 +0ms
  hci read local version - writing: 01011000 +0ms
  hci write LE host supported - writing: 016d0c020100 +0ms
  hci read LE host supported - writing: 016c0c00 +0ms
  hci read bd addr - writing: 01091000 +0ms
  hci onSocketData: 040e0401010c00 +11ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 3073 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401012000 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8193 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0c0101100006bb22060a00bb22 +2ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 4097 +0ms
  hci 		status = 0 +0ms
  hci 		result = 06bb22060a00bb22 +0ms
  hci set advertise enable - writing: 010a200100 +0ms
  hci set advertisement parameters - writing: 0106200fa000a0000000000000000000000700 +0ms
  hci onSocketData: 040e04016d0c00 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 3181 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e06016c0c000100 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 3180 +0ms
  hci 		status = 0 +0ms
  hci 		result = 0100 +0ms
  hci 			le = 1 +0ms
  hci 			simul = 0 +0ms
  hci onSocketData: 040e0a010910001271da7d1a00 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 4105 +0ms
  hci 		status = 0 +0ms
  hci 		result = 1271da7d1a00 +0ms
  hci address = 00:1a:7d:da:71:12 +1ms
  bleno addressChange 00:1a:7d:da:71:12 +0ms
  hci onSocketData: 040e04010a200c +0ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8202 +0ms
  hci 		status = 12 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401062000 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8198 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  bleno stateChange poweredOn +0ms
on -> stateChange: poweredOn
  gap startAdvertising: name = PM-HR-MONITOR-0, serviceUuids = [
  "180D"
] +4ms
  gap startAdvertisingWithEIRData: advertisement data = 02010603030d18, scan data = 1008504d2d48522d4d4f4e49544f522d30 +1ms
  hci set scan response data - writing: 01092020111008504d2d48522d4d4f4e49544f522d300000000000000000000000000000 +0ms
  hci set advertisement data - writing: 010820200702010603030d18000000000000000000000000000000000000000000000000 +0ms
  hci set advertise enable - writing: 010a200101 +0ms
  hci set scan response data - writing: 01092020111008504d2d48522d4d4f4e49544f522d300000000000000000000000000000 +0ms
  hci set advertisement data - writing: 010820200702010603030d18000000000000000000000000000000000000000000000000 +0ms
  hci onSocketData: 040e0401092000 +2ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8201 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401082000 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8200 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +1ms
  hci onSocketData: 040e04010a2000 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8202 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  bleno advertisingStart: null +0ms
on -> advertisingStart: success
  gatt handles = [
  {},
  {
    "type": "service",
    "uuid": "1800",
    "startHandle": 1,
    "endHandle": 5
  },
  {
    "type": "characteristic",
    "uuid": "2a00",
    "properties": 2,
    "secure": 0,
    "startHandle": 2,
    "valueHandle": 3
  },
  {
    "type": "characteristicValue",
    "handle": 3,
    "value": "Buffer('77732d6d6f727269732d7562756e7475', 'hex')"
  },
  {
    "type": "characteristic",
    "uuid": "2a01",
    "properties": 2,
    "secure": 0,
    "startHandle": 4,
    "valueHandle": 5
  },
  {
    "type": "characteristicValue",
    "handle": 5,
    "value": "Buffer('8000', 'hex')"
  },
  {
    "type": "service",
    "uuid": "1801",
    "startHandle": 6,
    "endHandle": 9
  },
  {
    "type": "characteristic",
    "uuid": "2a05",
    "properties": 32,
    "secure": 0,
    "startHandle": 7,
    "valueHandle": 8
  },
  {
    "type": "characteristicValue",
    "handle": 8,
    "value": "Buffer('00000000', 'hex')"
  },
  {
    "type": "descriptor",
    "handle": 9,
    "uuid": "2902",
    "properties": 14,
    "secure": 0,
    "value": "Buffer('0000', 'hex')"
  },
  {
    "type": "service",
    "uuid": "180D",
    "startHandle": 10,
    "endHandle": 17
  },
  {
    "type": "characteristic",
    "uuid": "2A37",
    "properties": 16,
    "secure": 0,
    "startHandle": 11,
    "valueHandle": 12
  },
  {
    "type": "characteristicValue",
    "handle": 12,
    "value": null
  },
  {
    "type": "descriptor",
    "handle": 13,
    "uuid": "2902",
    "properties": 14,
    "secure": 0,
    "value": "Buffer('0000', 'hex')"
  },
  {
    "type": "descriptor",
    "handle": 14,
    "uuid": "2901",
    "properties": 2,
    "secure": 0,
    "value": "Heart rate"
  },
  {
    "type": "characteristic",
    "uuid": "2A38",
    "properties": 2,
    "secure": 0,
    "startHandle": 15,
    "valueHandle": 16
  },
  {
    "type": "characteristicValue",
    "handle": 16,
    "value": null
  },
  {
    "type": "descriptor",
    "handle": 17,
    "uuid": "2901",
    "properties": 2,
    "secure": 0,
    "value": "Sensor location"
  }
] +1ms
  bleno servicesSet +1ms
setServices: success
  hci onSocketData: 040e0401092000 +3ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8201 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401082000 +4ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8200 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 043e13010045000101dc6c0088867b27000000d00701 +14s
  hci 	event type = 4 +0ms
  hci 	sub event type = 62 +0ms
  hci 		LE meta event type = 1 +0ms
  hci 		LE meta event status = 0 +0ms
  hci 		LE meta event data = 45000101dc6c0088867b27000000d00701 +0ms
  hci 			handle = 69 +1ms
  hci 			role = 1 +0ms
  hci 			address type = random +0ms
  hci 			address = 7b:86:88:00:6c:dc +0ms
  hci 			interval = 48.75 +1ms
  hci 			latency = 0 +0ms
  hci 			supervision timeout = 20000 +0ms
  hci 			master clock accuracy = 1 +0ms
  bleno accept 7b:86:88:00:6c:dc +1ms
accept
  hci onSocketData: 02450010000c00050012010800280038000000d007 +1ms
  hci 	event type = 2 +0ms
  mgmt on data ->0b0000000d00dc6c0088867b02000000000000 +0ms
  hci onSocketData: 0245200a0006000500130102000000 +154ms
  hci 	event type = 2 +0ms
  hci 		cid = 5 +0ms
  hci 		handle = 69 +1ms
  hci 		data = 130102000000 +0ms
  hci onSocketData: 0245200b0007000400100100ffff0028 +0ms
  hci 	event type = 2 +4ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +1ms
  hci 		data = 100100ffff0028 +0ms
  gatt handing request: 100100ffff0028 +3ms
  gatt read by group: startHandle = 0x1, endHandle = 0xffff, uuid = 0x2800 +1ms
  gatt response: 11060100050000180600090001180a0011000d18 +1ms
  gatt send: 11060100050000180600090001180a0011000d18 +0ms
  hci write acl data pkt - writing: 02450018001400040011060100050000180600090001180a0011000d18 +0ms
  hci onSocketData: 0245200b0007000400101200ffff0028 +87ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 101200ffff0028 +0ms
  gatt handing request: 101200ffff0028 +0ms
  gatt read by group: startHandle = 0x12, endHandle = 0xffff, uuid = 0x2800 +0ms
  gatt response: 011012000a +0ms
  gatt send: 011012000a +0ms
  hci write acl data pkt - writing: 024500090005000400011012000a +0ms
  hci onSocketData: 0245200b000700040008010005000228 +97ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 08010005000228 +0ms
  gatt handing request: 08010005000228 +1ms
  gatt read by type: startHandle = 0x1, endHandle = 0x5, uuid = 0x2802 +0ms
  gatt response: 010801000a +0ms
  gatt send: 010801000a +0ms
  hci write acl data pkt - writing: 024500090005000400010801000a +0ms
  hci onSocketData: 0245200b000700040008010005000328 +97ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 08010005000328 +0ms
  gatt handing request: 08010005000328 +0ms
  gatt read by type: startHandle = 0x1, endHandle = 0x5, uuid = 0x2803 +0ms
  gatt response: 09070200020300002a0400020500012a +0ms
  gatt send: 09070200020300002a0400020500012a +0ms
  hci write acl data pkt - writing: 02450014001000040009070200020300002a0400020500012a +0ms
  hci onSocketData: 0245200b000700040008050005000328 +146ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 08050005000328 +0ms
  gatt handing request: 08050005000328 +0ms
  gatt read by type: startHandle = 0x5, endHandle = 0x5, uuid = 0x2803 +0ms
  gatt response: 010805000a +0ms
  gatt send: 010805000a +0ms
  hci write acl data pkt - writing: 024500090005000400010805000a +0ms
  hci onSocketData: 0245200b000700040008060009000228 +97ms
  hci 	event type = 2 +1ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 08060009000228 +0ms
  gatt handing request: 08060009000228 +0ms
  gatt read by type: startHandle = 0x6, endHandle = 0x9, uuid = 0x2802 +0ms
  gatt response: 010806000a +0ms
  gatt send: 010806000a +0ms
  hci write acl data pkt - writing: 024500090005000400010806000a +0ms
  hci onSocketData: 0245200b000700040008060009000328 +97ms
  hci 	event type = 2 +1ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 08060009000328 +0ms
  gatt handing request: 08060009000328 +0ms
  gatt read by type: startHandle = 0x6, endHandle = 0x9, uuid = 0x2803 +0ms
  gatt response: 09070700200800052a +0ms
  gatt send: 09070700200800052a +1ms
  hci write acl data pkt - writing: 0245000d000900040009070700200800052a +0ms
  hci onSocketData: 0245200b000700040008080009000328 +95ms
  hci 	event type = 2 +1ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 08080009000328 +0ms
  gatt handing request: 08080009000328 +0ms
  gatt read by type: startHandle = 0x8, endHandle = 0x9, uuid = 0x2803 +0ms
  gatt response: 010808000a +0ms
  gatt send: 010808000a +1ms
  hci write acl data pkt - writing: 024500090005000400010808000a +0ms
  hci onSocketData: 0245200900050004000409000900 +96ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 0409000900 +0ms
  gatt handing request: 0409000900 +0ms
  gatt response: 050109000229 +1ms
  gatt send: 050109000229 +0ms
  hci write acl data pkt - writing: 0245000a0006000400050109000229 +0ms
  hci onSocketData: 043e0a0300450036000000d007 +47ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 62 +0ms
  hci 		LE meta event type = 3 +0ms
  hci 		LE meta event status = 0 +0ms
  hci 		LE meta event data = 450036000000d007 +0ms
  hci 			handle = 69 +0ms
  hci 			interval = 67.5 +0ms
  hci 			latency = 0 +0ms
  hci 			supervision timeout = 20000 +0ms
  hci onSocketData: 0245200b0007000400080a0011000228 +162ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 080a0011000228 +0ms
  gatt handing request: 080a0011000228 +0ms
  gatt read by type: startHandle = 0xa, endHandle = 0x11, uuid = 0x2802 +0ms
  gatt response: 01080a000a +0ms
  gatt send: 01080a000a +0ms
  hci write acl data pkt - writing: 02450009000500040001080a000a +0ms
  hci onSocketData: 0245200b0007000400080a0011000328 +135ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 080a0011000328 +0ms
  gatt handing request: 080a0011000328 +0ms
  gatt read by type: startHandle = 0xa, endHandle = 0x11, uuid = 0x2803 +0ms
  gatt response: 09070b00100c00372a0f00021000382a +1ms
  gatt send: 09070b00100c00372a0f00021000382a +0ms
  hci write acl data pkt - writing: 02450014001000040009070b00100c00372a0f00021000382a +0ms
  hci onSocketData: 0245200b000700040008100011000328 +134ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 08100011000328 +0ms
  gatt handing request: 08100011000328 +0ms
  gatt read by type: startHandle = 0x10, endHandle = 0x11, uuid = 0x2803 +0ms
  gatt response: 010810000a +0ms
  gatt send: 010810000a +0ms
  hci write acl data pkt - writing: 024500090005000400010810000a +0ms
  hci onSocketData: 024520090005000400040d000e00 +135ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 040d000e00 +0ms
  gatt handing request: 040d000e00 +0ms
  gatt response: 05010d0002290e000129 +0ms
  gatt send: 05010d0002290e000129 +1ms
  hci write acl data pkt - writing: 0245000e000a00040005010d0002290e000129 +0ms
  hci onSocketData: 0245200900050004000411001100 +134ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 0411001100 +0ms
  gatt handing request: 0411001100 +0ms
  gatt response: 050111000129 +0ms
  gatt send: 050111000129 +0ms
  hci write acl data pkt - writing: 0245000a0006000400050111000129 +0ms
  hci onSocketData: 043e0a0300450027000000d007 +674ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 62 +0ms
  hci 		LE meta event type = 3 +0ms
  hci 		LE meta event status = 0 +0ms
  hci 		LE meta event data = 450027000000d007 +0ms
  hci 			handle = 69 +0ms
  hci 			interval = 48.75 +2ms
  hci 			latency = 0 +0ms
  hci 			supervision timeout = 20000 +0ms
  hci onSocketData: 043e0a0300450036000000d007 +1s
  hci 	event type = 4 +0ms
  hci 	sub event type = 62 +0ms
  hci 		LE meta event type = 3 +0ms
  hci 		LE meta event status = 0 +0ms
  hci 		LE meta event data = 450036000000d007 +0ms
  hci 			handle = 69 +0ms
  hci 			interval = 67.5 +0ms
  hci 			latency = 0 +0ms
  hci 			supervision timeout = 20000 +0ms
  hci onSocketData: 0245200b0007000400100100ffff0028 +285ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 100100ffff0028 +0ms
  gatt handing request: 100100ffff0028 +0ms
  gatt read by group: startHandle = 0x1, endHandle = 0xffff, uuid = 0x2800 +0ms
  gatt response: 11060100050000180600090001180a0011000d18 +0ms
  gatt send: 11060100050000180600090001180a0011000d18 +0ms
  hci write acl data pkt - writing: 02450018001400040011060100050000180600090001180a0011000d18 +1ms
  hci onSocketData: 0245200b0007000400101200ffff0028 +134ms
  hci 	event type = 2 +0ms
  hci 		cid = 4 +0ms
  hci 		handle = 69 +0ms
  hci 		data = 101200ffff0028 +0ms
  gatt handing request: 101200ffff0028 +0ms
  gatt read by group: startHandle = 0x12, endHandle = 0xffff, uuid = 0x2800 +0ms
  gatt response: 011012000a +0ms
  gatt send: 011012000a +0ms
  hci write acl data pkt - writing: 024500090005000400011012000a +0ms
  hci onSocketData: 04050400450013 +204ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 5 +0ms
  hci 		handle = 69 +0ms
  hci 		reason = 19 +0ms
  bleno disconnect7b:86:88:00:6c:dc +1ms
disconnect
  hci set advertise enable - writing: 010a200101 +0ms
  mgmt on data ->0c0000000800dc6c0088867b0203 +0ms
  hci onSocketData: 040e04010a2000 +27ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8202 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  mgmt on data ->0b0001000d00dc6c0088867b02000000000000 +1s
  hci onSocketData: 040e04010b2000 +1ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8203 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e04010c2000 +2ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8204 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  mgmt on data ->0c0001000800dc6c0088867b0203 +6s
  hci onSocketData: 040e04010c2000 +34s
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8204 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  mgmt on data ->050001000000 +11ms
  mgmt on data ->040001000000 +735ms


HCI1 stopped advertising.

**Comment by TomThats** [comment]
I have the same problem on a raspberry pi 3 running two USB Bluetooth Sticks.

Both have their own device assigned via BLENO_HCI_DEVICE_ID.

If I run the scripts with all debug info, I can see that both scripts receive the same data from the sockets even though just one is used with an app.


Script #1:
```
  hci set advertise enable - writing: 010a200101 +1ms
  mgmt on data ->0c0000000800c44b8bf78a440203 +0ms
  hci onSocketData: 040e04010a2000 +54ms
  hci 	event type = 4 +1ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8202 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
```

Script #2:
```
 bleno servicesSet +5ms
  hci onSocketData: 040e0401092000 +0ms
  hci 	event type = 4 +0ms
  hci 	sub event type = 14 +1ms
  hci 		cmd = 8201 +0ms
  hci 		status = 0 +0ms
  hci 		result =  +0ms
  hci onSocketData: 040e0401082000 +0ms
  hci 	event type = 4 +1ms
  hci 	sub event type = 14 +0ms
  hci 		cmd = 8200 +0ms
  hci 		status = 0 +1ms
  hci 		result =  +0ms
  mgmt on data ->0b0000000d00c44b8bf78a4402000000000000 +13s
  mgmt on data ->0c0000000800c44b8bf78a440203 +3s
```

I'm not a expert but that shouldn't happen if both scripts use their own device, or am I wrong?

**Comment by sandeepmistry** [comment]
Hi @mhoresh, @rodrigosalinas, @TomThats,

Could you please try the latest master version `npm install sandeepmistry/bleno`. It uses the latest `bluetooth-hci-socket` version that includes the following fix: https://github.com/sandeepmistry/node-bluetooth-hci-socket/commit/14dc3660f9e86695c6c75b92dc2222da2905549e

Let me know if it works, then I can publish a new version to npm.

**Comment by mhoresh** [comment]
It seems to be working well for me. Thank you.
