### ISSUE TITLE
How to advertise without request

### ISSUE THREAD

**Issue by bzhong2** [sandeepmistry/bleno#209]
I noticed that for the example "pizza", noble  has to send a "reading request" signal first to the bleno to read data from bleno. How can I let bleno to continuously streaming data just when a noble is connected without any reading request? I want to emulate the bleno (on windows10) as a wearable sensor which can continuously stream data to android phone.

**Comment by sandeepmistry** [comment]
Hi @bzhong2,

It sounds like you want a characteristic that has a notify property. Then the central can subscribe to this and the bleno peripheral can push data.

Please see the echo example for how to push data.
