### ISSUE TITLE
UNABLE to npm install bleno!!!

### ISSUE THREAD

**Issue by MussabNuri** [sandeepmistry/bleno#212]
i've been trying to Install Bleno via Node.js Package Manager (npm), it fails to do so, and gives me the erros : 
npm WARN optional Skipping failed optional dependency /bleno/xpc-connection:
npm WARN notsup Not compatible with your operating system or architecture: xpc-connection@0.1.4
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.

**Comment by sandeepmistry** [comment]
@MussabNuri this is fine, all warnings. `xpc-connection` is an optional dependency needed for OS X only.
