### ISSUE TITLE
Characteristic.onUnsubscribe not called on disconnect

### ISSUE THREAD

**Issue by adi1133** [sandeepmistry/bleno#214]
When a bluetooth device gets disconnected, it's notify listeners remain active.

**Comment by jor3l** [comment]
+1

**Comment by henla464** [comment]
+1

**Comment by sandeepmistry** [comment]
Hi @adi1133, @jor3l, @henla464,

This has been implemented in https://github.com/sandeepmistry/bleno/commit/1a3cbd49bbaf7d024faa4e0a8d3bc4d17d25cc99. Please try it our via `npm install sandeepmistry/bleno` and provide your feedback.

**Comment by mattsson** [comment]
We're having the same issue. When will this be released?

**Comment by sandeepmistry** [comment]
@mattsson I've published v0.4.2 to npm now.

**Comment by mattsson** [comment]
@sandeepmistry Cool, thanks.

**Comment by erezc74** [comment]
Hi @sandeepmistry, 
Was this issue fixed in 0.4.2?
I'm using 0.4.2 and still onUnsubscribe not being called on disconnect.
I'm wondering if there is an issue on my end or maybe it wasn't fixed yet?
10x.

**Comment by erezc74** [comment]
Hi @sandeepmistry ,
Fixed it by adding the code in [1a3cbd4](https://github.com/sandeepmistry/bleno/commit/1a3cbd49bbaf7d024faa4e0a8d3bc4d17d25cc99) manually.
10x
