### ISSUE TITLE
Not able to stop bluetoothd BlueZ >= 5.14

### ISSUE THREAD

**Issue by dneykov** [sandeepmistry/bleno#215]
Hi everyone,
I'm having trouble disabling bluetoothd.
When I try stopping bluetoothd with 
sudo service bluetooth stop
Everything is fine bluetoothd is stopped and bleno works.
But when I try sudo update-rc.d bluetooth remove
nothing happen bluetoothd is still active and running ( checking with service bluetooth status)

I'm using Raspbian 4.4 (Jessie). Strange thing is that on one raspberry is working ( bluetoothd is disabled) but on another is not working. Both uses same OS and everything.

Any help will be appreciated. Thanks

**Comment by sandeepmistry** [comment]
Seems solved by https://github.com/sandeepmistry/bleno/issues/24#issuecomment-241405304, closing.
