### ISSUE TITLE
Bleno discontent when another handle disconnect

### ISSUE THREAD

**Issue by AlessandroFerri** [sandeepmistry/bleno#219]
In solving the issue #210, I found issue which in turn I have solved.
I am going to explain the issue.
It was my need to be free to connect/disconnect my iPad to my Rpi3 through my bleno service code and at the same time being free to connect my RPi3 to my old Rpi2 (Speaker) via a a2dp service to send music from RPi3 to RPi2.
The issue is that when I disconnect the A2DP service RPi3 to RPi2, even my iPad on bleno service was disconnected, ie bleno saw the disconnection of a2dp RPi2 as a disconnection of the iPad client.

I hope to have been clear!!!!

Anyway I have already solved the issue by modifying the code /lib/hci-socket/hci.js
I am sure that the change must be optimized and I ask Sandeep Mistry to verify the code.
I attach the file, below.
[hci.txt](https://github.com/sandeepmistry/bleno/files/435374/hci.txt)

**Comment by sandeepmistry** [comment]
@AlessandroFerri thanks for sharing your patch. Please open a pull request so we can further discuss integrating your changes.
