### ISSUE TITLE
disconnect frequently on linux while stays connected on mac

### ISSUE THREAD

**Issue by chirag04** [sandeepmistry/bleno#226]
Hi @sandeepmistry 

I noticed that after connecting to the peripheral, discovering services, reading one characteristics, i would get disconnect event after some time on linux. 

However on macbook, the connection stay open until i disconnect the central manually.

Is this a know behavior to get disconnects when the connection is idle?

btw, thanks for the awesome lib.

**Comment by sandeepmistry** [comment]
Hi @chirag04,

Please share the following:
* bleno app you are using
* debug logs: `sudo DEBUG=* node <file>.js`
* HCI dump capture: `sudo hcidump -t -x`
* kernel version: `uname -a`
