### ISSUE TITLE
BLE 4.2 Security with Bleno

### ISSUE THREAD

**Issue by reallyroy** [sandeepmistry/bleno#227]
Hi Sandeep,

This is a question, not an issue.

After some reading I realized I need to use Bleno rather than Noble. I wanted to know if Bleno supports BLE 4.2's ECDH security feature. If so, how do I set something like that? 

Regards,
Roy

**Comment by sandeepmistry** [comment]
Hi @reallyroy.

ECDH is not supported. The `smp.js` file will have to be modified to include support for it. We'd also need to stop the kernel from interfering via `sudo hciconfig hci0 down` + `sudo HCI_CHANNEL_USER=1 node <file>.js`.

It would be great if you had time to dive in and submit a pull request.
