### ISSUE TITLE
Try to send very long data 

### ISSUE THREAD

**Issue by ronyad** [sandeepmistry/bleno#229]
Hey im try to send very large amount of  data to my IOS app.
I got that mtu is 158 bytes, so I expect that onReadRequest will called multiple times, however, the function is call exactly 4 times, so I can send only 4*158 =± 630 bytes.
Am I doing wrong? or it there better good practice how to send large amount of data?
My plans is to build live stream service.

My code it like:

var bleno = require('bleno');
var os = require('os');
var util = require('util');
var fs = require('fs');
var BlenoCharacteristic = bleno.Characteristic;

var HelloCharacteristic = function() {
 HelloCharacteristic.super_.call(this, {
    uuid: 'ff51b30e-d7e2-4d93-8842-a7c4a57dfb10',
    properties: ['read']
  });
    this._value = new Buffer(0);
};

HelloCharacteristic.prototype.onReadRequest = function(offset, callback) {
  if(!offset) {
data = fs. readFileSync("/tmp/story.txt")
this._value = new Buffer(data)
  } 
  callback(this.RESULT_SUCCESS, this._value.slice(offset, this._value.length));
};

HelloCharacteristic.prototype.properties = ['read','writeWithoutResponse']
util.inherits(HelloCharacteristic, BlenoCharacteristic);
module.exports = HelloCharacteristic;

**Comment by sandeepmistry** [comment]
Hi @ronyad,

Your code looks ok to me. Please keep in mind the maximum value of a characteristic is 512 bytes. So I think iOS will not try to read beyond this. I would suggest building another protocol on top of GATT to transfer your data.
