### ISSUE TITLE
'index out of range' when central tries to unsubscribe

### ISSUE THREAD

**Issue by empinator** [sandeepmistry/bleno#23]
Hi, 

I wrote a notifier service based on the given examples, but when noble is trying to unsubscribe from bleno's with this command:
`characteristic.notify(false, notify._notifyDisable);`

bleno is crashing with an 'index out of range'

```
buffer.js:604
    throw new RangeError('index out of range');
          ^
RangeError: index out of range
    at checkInt (buffer.js:604:11)
```

_Peripheral:_ 
Machine: Raspberry PI, Kernel 3.6.11+, Bluez 5.8, GBU521 Dongle
code: http://pastebin.com/bpUBihb5
console output: http://pastebin.com/2qwBY91p

_Central:_
Machine: Thinkpad T400s, Kernel 3.5.0-45-generic, Bluez 5.8, GBU521 Dongle
code: http://pastebin.com/Esa5xhvz
console output: http://pastebin.com/jZ81CgMM

any idea?
Thanks.

**Comment by paixaop** [comment]
I also faced a similar problem but in my case the error was in my code the call to `writeUInt32LE` needs 4 bytes and I had initialized the `value` to a single byte buffer with `Buffer.alloc(1)`.

Changing it to `value: Buffer.alloc(4)` in the appropriate characteristic class solved the issue. 

```
new Bleno.Descriptor({
     // Client Characteristic Configuration
     uuid: '2902',
     value: Buffer.alloc(4)
}),
```
