### ISSUE TITLE
Error when install bleno via npm

### ISSUE THREAD

**Issue by wanghongjuan** [sandeepmistry/bleno#232]
Hi, @sandeepmistry 
There is an error occurred when install this package via npm on my Intel Edison with [Ostro OS], the log message show as below:
```
root@edison:/tmp# npm install bleno
npm WARN optional dep failed, continuing xpc-connection@0.1.4
-
> usb@1.2.0 install /tmp/node_modules/bleno/node_modules/bluetooth-hci-socket/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v46-linux-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp)
...
```
The `usb_bindings-v1.2.0-node-v46-linux-ia32.tar.gz` can not found in [github], but the `bleno` can be required and the all [tests] are pass after install this package. Is there anything wrong?

[Ostro OS]: https://ostroproject.org/
[github]: https://github.com/tessel/node-usb
[tests]: https://github.com/sandeepmistry/bleno/tree/master/test

**Comment by sandeepmistry** [comment]
Hi @wanghongjuan,

This should be fine, please let me know if one of the built-in bleno examples don't function.

` xpc-connection` is only needed on OS X and `usb` is only needed on Windows (optional for Linux).
