### ISSUE TITLE
Change Device UUID

### ISSUE THREAD

**Issue by HippoBaro** [sandeepmistry/bleno#237]
I'm trying to change my device UUID. I can set my services and characteristics UUIDs, but not my device's.

![img_0313](https://cloud.githubusercontent.com/assets/6069928/19438206/ffb2f4fe-9478-11e6-8553-311b166c0a5d.PNG)

Here for example BlueLight reports that my device UUID is *5E7EF70B-224B-491B-86DB-2DA3BA8AF437*. It does not seem to be random, stopping and restarting my application doesn't change it.

**How can I change this using Bleno ?** Thanks !

**Comment by sandeepmistry** [comment]
@HippoBaro it is not possible to change the device UUID with bleno.

iOS bases it off the peripherals Bluetooth Address, and it is a randomly generated UUID per iOS device.
