### ISSUE TITLE
Increase MTU

### ISSUE THREAD

**Issue by boaerosuke** [sandeepmistry/bleno#248]
How can I increase the value size of a characteristic to more then 23 bytes which is the standard?
Is the size (MTU) capped by the capability of a central device? (in my case iOS)

I tried to increase the MTU in gatt.js from 23 to something above (and also the MaxMTU so that it fits).
Eventhough the iOS device offers an MTU of 185 in the first negotiation, Bleno succeeds to let the ios device read data which is bigger.

In my case it was at least 672 byte. But as soon as I increase it to something above 672 Bleno just does not respond. Is this a bug or is it simply not possible?

In case of that fact that it is not possible, is there another possibility to transmit data that might have at least 1024 byte or more?

**Comment by sandeepmistry** [comment]
This library will adjust the MTU to whatever the central negotiates.

For long reads, you must use the the `offset` parameter of the callback to supply the correct offset in data.

I'm going to close this for now, if you still face issues please provide a minimal sample bleno app to reproduce the issue along with specific sequence of steps to follow.

**Comment by boaerosuke** [comment]
Thank you very much for your response!
I´am playing with your Bleno example and was wondering how to increase the size of the data that has been read onReadRequest.

You wrote I need to use the offset parameter of the callback to supply the correct offset in data

Do you mean the offset in .onReadRequest?

`EchoCharacteristic.prototype.onReadRequest = function(offset, callback) {
  console.log ('onReadRequest Offset: ' + offset.toString());
  //console.log('EchoCharacteristic - onReadRequest: value = ' + this._value.toString('utf8')); 
  callback(this.RESULT_SUCCESS, this._value);
};`

If this is the offset you mentioned, could you tell me where exactly I can configure or increase it? since at this point the log of the offset provides 0, and changing this to another value inside of that function does not have any effect.

Any ideas?

My Goal is to increase the size of the value that has been read. I hope you could unterstand my issue here :)

Again thx for your stuff!

**Comment by WayneKeenan** [comment]
Just a FYI:
The Bluetooth LE Stack on your peripheral AND central devices needs to both support the "BLE 4.2 Data Length Extension" to be able to transfer packets up to around 240 bytes.

You might want to confirm that both your devices do support it.

Just a note, as it's not a perfect world I had to disable the BLE DLE on a peripheral so some older macOS laptops could talk to it. Such are the nature of 'standard extensions' I guess.

**Comment by boaerosuke** [comment]
Yes, thx for the info :) I´ll keep that in mind.

Increasing the MTU already increased the amount of data that could be read by my central.
But it is not enough, thats why I try to use the offset stuff to see which effects I can achieve.

**Comment by sandeepmistry** [comment]
@boaerosuke please see: https://github.com/sandeepmistry/bleno/blob/master/test.js#L50-L75
