### ISSUE TITLE
Distinguishing between multiple subscribers?

### ISSUE THREAD

**Issue by mattpat** [sandeepmistry/bleno#254]
I'm having some trouble figuring out how to distinguish between multiple subscribers for a particular characteristic.

If I'm understanding correctly, it looks like only one update value callback is ever stored on the characteristic. If multiple centrals subscribe, does onSubscribe get called more than once? Or does bleno paper over that? In other words, does bleno do "reference counting" for subscribers so that you only have to call one callback and it notifies all subscribers for you? Or do you need to maintain your own list of callbacks to support multiple subscribers?

More importantly, if bleno *doesn't* do reference counting, onUnsubscribe doesn't take any parameters, so how can you identify which central unsubscribed?

**Comment by sandeepmistry** [comment]
@mattpat bleno currently only supports one connected central at a time.
