### ISSUE TITLE
onConnect / onDisconnect

### ISSUE THREAD

**Issue by mattotodd** [sandeepmistry/bleno#262]
Is there a way to find out when a connection has been established, or when it disconnects?

Connecting via Noble using `peripheral.connect`

**Comment by sandeepmistry** [comment]
@mattotodd please see:

 * https://github.com/sandeepmistry/bleno#accept
* https://github.com/sandeepmistry/bleno#disconnect

**Comment by mattotodd** [comment]
thx

**Comment by mattotodd** [comment]
Curious why `disconnect is not supported on OS X!`.   Both listening to disconnects from central, or forcibly disconnecting via peripheral side.

Does work just need to be done, or is this a limit with the OS?
