### ISSUE TITLE
Unable to run without sudo even after setcap

### ISSUE THREAD

**Issue by shekit** [sandeepmistry/bleno#263]
Hi,

I'm using bleno in an electron app on the raspberry pi3. Everything works but it only works if I use sudo. Otherwise I get the warning: adapter state unauthorized, please run as root.

I installed setcap and ran the recommended command to be able to run without root but it doesn't seem to help at all.

Appreciate any help!

**Comment by sandeepmistry** [comment]
@shekit since you're probably not using using `node` to launch you electron app, just run `sudo setcap cap_net_raw+eip <blah>` on the tool/command you are launching instead.

**Comment by sandeepmistry** [comment]
Closing this for now, I think it's answered.

**Comment by shekit** [comment]
Yes thank you! Sorry didn't confirm this earlier
