### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ddddd9999333** [sandeepmistry/bleno#270]
Hello 

Running Ubuntu 16 I

apt-get remove nodejs
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get install -y nodejs
ln -s /usr/bin/nodejs /usr/bin/node

install prereqs as per project page
check version of node and npm show
v6.9.5 and 3.10.10

then I 
npm install bleno
I see:                (note home dir substituted for my home directory)
node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v48-linux-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@6.9.5 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "<home dir>/Downloads/noble-master/node_modules/usb/.node-gyp"
make: Entering directory '<home dir>/Downloads/noble-master/node_modules/usb/build'
make: *** No rule to make target '../.node-gyp/6.9.5/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '<home dir>/Downloads/noble-master/node_modules/usb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=<home dir>/Downloads/noble-master/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=<home dir>/Downloads/noble-master/node_modules/usb/src/binding"
gyp ERR! cwd <home dir>/Downloads/noble-master/node_modules/usb
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=<home dir>/Downloads/noble-master/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=<home dir>/Downloads/noble-master/node_modules/usb/src/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (<home dir>/Downloads/noble-master/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-31-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "<home dir>/Downloads/noble-master/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd <home dir>/Downloads/noble-master/node_modules/usb
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=<home dir>/Downloads/noble-master/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=<home dir>/Downloads/noble-master/node_modules/usb/src/binding' (1)
noble@1.7.0 <home dir>/Downloads/noble-master
└── bleno@0.4.1 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@~0.1.4 (node_modules/bleno/node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by sandeepmistry** [comment]
Seems like a permission error to me:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.9.5"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/Downloads/noble-master/node_modules/usb/.node-gyp"
```

I would suggest trying:

```
sudo -rm -rf /root/.node-gyp/6.9.5
```

Then re-installing. To me this is not an issue with bleno, but something to do with your dev environment.
