### ISSUE TITLE
Can this support Bluetooth 4.2 version?

### ISSUE THREAD

**Issue by gyloh9210** [sandeepmistry/bleno#272]
Hi there, I was wondering can noble support up to bluetooth 4.2 version? I am using my internal built-in bluetooth inside my laptop but I could not get it working. It is keeping loading and no responding at all when I run node index.js or node test.js. Please help.

**Comment by sandeepmistry** [comment]
@gyloh9210 should be fine, I suggest you try one of the examples in the examples folder.

**Comment by Uniphix** [comment]
@sandeepmistry I am actually trying to get it working with Raspberry PI 3 Model B+ which by default is now 4.2.  My code works fine with 4.0 Bluetooth but when we try on 4.2 it doesn't work
