### ISSUE TITLE
How to properly send integer, float and binary values

### ISSUE THREAD

**Issue by anchetaWern** [sandeepmistry/bleno#276]
Hi! I'm using Bleno for handling the code for a BLE peripheral while this Cordova plugin handles the code for the central device: https://github.com/don/cordova-plugin-ble-central
My question is, is there a standard or recommended way of sending integer or float values using Bleno? In such a way that it can be easily converted back to its original data when it arrives on the client-side.

Here's the code that I'm currently using for sending integer and float values:

```javascript
BatteryCharacteristic.prototype.onSubscribe = function(maxValueSize, updateValueCallback) {

  setInterval(function() {
    
    var rand_int = randomInt(); // generate random int
    
    var buf = new Buffer(1);
    buf.writeUInt8(parseInt(parseInt('0x' + rand_int).toString(16)), 0);
   /*
   // for float:
   var float_val = randomFloat(); // generate random float
   var buf = new Buffer(8);
   buf.writeFloatBE(val, 0);
   */
    updateValueCallback(buf);
   
  }, 1000);
}; 
```

The ArrayBuffer then arrives on the client-side and I convert them to their original values using DataView:

var dv = new DataView(buffer);
var original_int_value = dv.getUint8(0);
// var original_float_value = dv.getFloat32(0).toFixed(2);

This works but if there's a better (more standard) way of doing this then I'd like to know. My main concern is maintaining the data integrity when its being converted. When I want to send higher values or higher precision values, would this method still work.

Also, how do I go about sending binary values?

Thanks in advance!

**Comment by sandeepmistry** [comment]
That looks fine, I suggest you look at the Node.js Buffer API docs: https://nodejs.org/api/buffer.html

Treat binary numbers just like ints, and choose a 8, 16 or 32 -bit size.
