### ISSUE TITLE
is there any library for node.js or extension for building EIR ?

### ISSUE THREAD

**Issue by mdarweash** [sandeepmistry/bleno#277]
do i need to compile the whole thing and just insert it as a stringed buffer ? or there's is a way to build it dynamically using some functions with lead to the proper buffer ?

i'm asking as if there's no way for this, i may start implementing an easy way & see how can we integrate this in BLENO

sample code for the same thing on C

` ble.gap().accumulateAdvertisingPayload(GapAdvertisingData::KEYBOARD);
        ble.gap().accumulateAdvertisingPayload(GapAdvertisingData::COMPLETE_LOCAL_NAME,
                (const uint8_t *) DEVICE_NAME.data(), sizeof (DEVICE_NAME));
        ble.gap().accumulateAdvertisingPayload(GapAdvertisingData::SHORTENED_LOCAL_NAME,
                (const uint8_t *) DEVICE_NAME.data(), sizeof (DEVICE_NAME));
`

**Comment by sandeepmistry** [comment]
>do i need to compile the whole thing and just insert it as a stringed buffer ? or there's is a way to build it dynamically using some functions with lead to the proper buffer ?

You need to compose the whole buffer using the Node.js buffer API: https://nodejs.org/api/buffer.html

I've only scene advlib for decoding: https://www.npmjs.com/package/advlib
