### ISSUE TITLE
discoverServices returns no services (Pizza Example, Edison)

### ISSUE THREAD

**Issue by mklingles** [sandeepmistry/bleno#278]
I'm running the Pizza example on two edisons one as peripheral and one as central.  Connection works, but discoverServices is returning an empty array of services

I've attached an hcidump from both edisons.
[centralDump.txt](https://github.com/sandeepmistry/bleno/files/836136/centralDump.txt)
[peripheralDump.txt](https://github.com/sandeepmistry/bleno/files/836137/peripheralDump.txt)

**Comment by sandeepmistry** [comment]
@mklingles it doesn't look like bluetoothd is stopped as per the read me: https://github.com/sandeepmistry/bleno#linux

Feel free to re-open if that is not the case.
