### ISSUE TITLE
Sending and Receiving between Raspberry pi 3 and Android

### ISSUE THREAD

**Issue by newbielinuxuser** [sandeepmistry/bleno#280]
I've install Bleno in my raspberry pi 3, currently im able to send some plain text from android to raspberry pi 3, so how do i send some string back to Android ? Because I've tested with the callback function of onWriteRequest under new characteristic doesn't work, or are there any ways to trigger the writing part?

echo.js
`onWriteRequest : function(data , offset, withoutResponse, callback) {
	this.value = data;
	...
	if(this.value.toString == 'received_some_text_from_android') {
		// send plain text back to android
	}
}`

p/s: i'm very new to this, please bear with my false assumption

**Comment by storm1er** [comment]
same problem, if someone can give us a real ping pong example, that could be awesome :)

**Comment by newbielinuxuser** [comment]
Agree with the ping pong example, would be glad if there's sample about it =D

**Comment by newbielinuxuser** [comment]
@storm1er you found the solution ?

**Comment by storm1er** [comment]
Nope, I stop working on it for a time.
We just 'restart' the project with a friend, still no solution :( RPi seems ok but app still crashing on writeRequest

**Comment by WayneKeenan** [comment]
Perhaps taking a look at the Echo example will help you?

https://github.com/sandeepmistry/bleno/blob/master/examples/echo/characteristic.js

**Comment by newbielinuxuser** [comment]
@storm1er so your RPi(bleno) can do write request??

**Comment by newbielinuxuser** [comment]
@WayneKeenan thanks, will try to explore into that

**Comment by newbielinuxuser** [comment]
@storm1er noted, couldn't get it work yet, temporary KIV for this. I take it as April 5 ? cuz March 5 is like ... 3 weeks ago lol

**Comment by storm1er** [comment]
@newbielinuxuser yup, April obviously, sry ...

**Comment by storm1er** [comment]
Hey guys, great news, i'm close to the end \o/
I'm able to search, connect & read =)
I just did soe test on write, no crash as i had before. Have to do some cleaning & comment and i'll send a PR there.

ETA : 1 day

**Comment by storm1er** [comment]
Hey !!!

using https://github.com/sandeepmistry/bleno on RPi : 
setService : https://github.com/storm1er/323-Rpi/blob/master/rpi/index.js#L23-L30
onReadRequest / on WriteRequest : https://github.com/storm1er/323-Rpi/blob/master/rpi/characteristics/relais_1.js#L26-L41

using https://github.com/evothings/cordova-ble on Android :
ReadCharacteristics : https://github.com/storm1er/323-Rpi/blob/master/android/libs/app.js#L462-L499
WriteCharacteristics : https://github.com/storm1er/323-Rpi/blob/master/android/libs/app.js#L176-L183

I have to comments more as ui text is in French.
If you want to ask somethings, i'm here =)

**Comment by newbielinuxuser** [comment]
holy!! dam, you did it! trying these out =D 
will update you a.s.a.p

**Comment by sandeepmistry** [comment]
Closing this as resolved. It would be great if someone could open a pull request for a Read + Write example.

**Comment by storm1er** [comment]
@sandeepmistry I would like to do it, but as it depends on two repo, i don't really know how to do it "the clean way"

I thought about put an new folder in example folder, then put a link to the cordova-ble/example folder, is that good ?

**Comment by sandeepmistry** [comment]
@storm1er just a simple read write example in a new folder from "scratch" would be great.

**Comment by storm1er** [comment]
@sandeepmistry I'll do it ;)
ETA : 1 week (05.08.2017)

**Comment by houcem22** [comment]
hello everyone  :). @newbielinuxuser :  Can you please give me a link for a how-to send a string from android to raspberry pi 3. Thank you.
