### ISSUE TITLE
stopAdvertising callback is never called

### ISSUE THREAD

**Issue by manthis** [sandeepmistry/bleno#281]
I'm trying to get a confirmation that stopAdvertising works as expected. However, the callback is never called in my code:

> bleno.stopAdvertising(function() {
    console.log('Advertising stopped!');
});

I have also tried using the "on" event:

> bleno.on('advertisingStop', function() {
   console.log('Stopping advertising...');
});

But it also doesn't work. I'm on a Raspberry Pi 3 running last version of node.

**Comment by leviathan88** [comment]
if and when you want to stop advertising you simply call
`bleno.stopAdvertising()`
you can also have a listener
```
bleno.on('advertisingStop', ()=> {
  console.log('The bleno.stopAdvertising() has just been called")
})
```

**Comment by manthis** [comment]
Got you. Thank you very much.

**Comment by sandeepmistry** [comment]
@manthis are you still seeing this?

I just tried adding to the `test.js` in this repo and the callback was called. Tested on macOS and a Raspberry Pi 3.

```
setTimeout(function() {
  bleno.stopAdvertising(function() {
    console.log('Advertising stopped!');
  });

}, 5000);
```
