### ISSUE TITLE
How to pass data bigger than 20bytes via indicate/updateValueCallback ?

### ISSUE THREAD

**Issue by leviathan88** [sandeepmistry/bleno#285]
First of all Bleno is great!,

My client (nRF Connect app) can receive only 20bytes per message, 
for example if my message is 
`this.message= new Buffer("you are my sunshine my only sunshine"`)
in read request here is how I send it back
```
onReadRequest(offset, callback) {
        if (offset) {
            callback(this.RESULT_SUCCESS, this.message.slice(offset))
        } else {              
            callback(this.RESULT_SUCCESS, this.message)
        }
    }
```

using it like this I manage to send the complete message,
but how can I achieve this in Indicate, that is with this._updateValueCallback ?

just to test it out, I tried a _for_ loop, and sending chunks of data
`this._updateValueCallback(this.message.slice(startIndex,endIndex)`
but in the app (nRF Connect) I only receive/see the last part of the message,
in my case _" only sunshine"_,

how can I send the complete message ? (I mean I send the whole message, but since it comes in packets, I only get the last one, and I want the full message - just like you get it in onReadRequest although it sends it here separately too, when it's too big)

**EDIT:**
after reading about similar issues,
I did find out about onIndicate method,
but the thing is I'm not getting the full message (as I do in onReadRequest)
I get it in parts so I end up with the same result as with a _for_ loop, in nRF App I get the value: _" only sunshine"_,
and I want the full message, as I get in onReadRequest

here is how my code looks:

```
onSubscribe(maxValueSize, updateValueCallback) {
        this._maxValueSize = maxValueSize //it's 20!
        this._updateValueCallback = updateValueCallback
    }

indicateClient() {
        this.message = Buffer.isBuffer(this.message) ? this.message : new Buffer(this.message)
        if (this._updateValueCallback) {
            let value = this.getNextChunk(this.message)
            if (value.length > 0) {
                this._updateValueCallback(value)
            }
        } else {
            console.log('pure emptinesss')
        }
    }

onIndicate() {
        this.indicateClient()
    }

getNextChunk(data) {
        let chunk
        if (data.length > this._maxValueSize) {
            chunk = data.slice(0, this._maxValueSize)
            this.message = data.slice(this._maxValueSize)
        } else {
            chunk = data
            this.message = new Buffer(0)
        }
        return chunk
    }
```

it's also worth mentioning that, as others have reported,
onIndicate() is only called on first indicate event, unless you add some setTimeout
inside indicateClient

**Comment by sandeepmistry** [comment]
@leviathan88 unfortunately notifications are limited by the MTU of the central.

You'll have to develop your own protocol to split up the data over notifications.

**Comment by leviathan88** [comment]
yeah figured that out :), either way thanks a lot !

**Comment by CBZakaria** [comment]
Hello @leviathan88 did you solve your problem?

**Comment by leviathanbeak** [comment]
Hi @CBZakaria  yes I did but don't remember how :/ sorry
