### ISSUE TITLE
Number of packets sent

### ISSUE THREAD

**Issue by almirbi** [sandeepmistry/bleno#287]
Hello,

I am using bleno to send BLE packets from OS X to an Arduino board with the nRF24L01+ radio module (bit banging).

Now I want to test the reliability of the connection and see how many packets make it to the nRF. How can I count the number of packets that are sent with ```bleno.startAdvertising()```?

Thank you

**Comment by sandeepmistry** [comment]
There's no reliable way, the advertisement rate should be 100ms on OS X, so a timer is the best way to estimate ...
