### ISSUE TITLE
Cannot advertise iBeacon and with EIR data - 'Command Not Allowed'

### ISSUE THREAD

**Issue by carlospuk** [sandeepmistry/bleno#292]
Using bleno on Raspian (with a Pi 3) I want to advertise both a peripheral and also an iBeacon - however, if I execute the code below, then I get the following error in the console.  Is it not possible to advertise both as an iBeacon and also a peripheral simultaneously?

     console.log('Starting peripheral advertising:')
     bleno.startAdvertisingWithEIRData(adPayload, null, function(err) {  //bleno.startAdvertising(name, [TicketService.uuid], function(err) {
      if (err) {
        console.log(err);
      }
      else {
        console.log('...done.');

      // iBeacon Advertising
      console.log('Starting iBeacon advertising:')
      var minor = 0; // 0x0000 - 0xffff
      var measuredPower = -59; // -128 - 127
      bleno.startAdvertisingIBeacon(IBEACON_UUID, DEVICE_ID, minor, measuredPower, function(err) {
        if (err) {
          console.log(err);
        }
        else {
          console.log('...done.');
        }
      });

        }
      });

`
Error: Command Disallowed
    at Gap.onHciLeAdvertiseEnableSet (/home/pi/bleno-master/lib/hci-socket/gap.js:201:15)
    at emitOne (events.js:96:13)
    at Hci.emit (events.js:191:7)
    at Hci.processCmdCompleteEvent (/home/pi/bleno-master/lib/hci-socket/hci.js:542:10)
    at Hci.onSocketData (/home/pi/bleno-master/lib/hci-socket/hci.js:428:12)
    at emitOne (events.js:96:13)
    at BluetoothHciSocket.emit (events.js:191:7)
`

**Comment by sandeepmistry** [comment]
> Is it not possible to advertise both as an iBeacon and also a peripheral simultaneously?

Correct, only one at a time is supported. You'll have to call `stopAdvertising` before starting.
