### ISSUE TITLE
how can I update other characteristic's value when onWriteRequest?

### ISSUE THREAD

**Issue by DanielTimLee** [sandeepmistry/bleno#296]
For Example, there are 3 characteristics, **header, data, result characteristics**. 
I'd like to update result characteristics when header has written, or data has written. (for verifying that each header or data has been written successfully.)

And also, by updating result characteristics, it notifies itself, because other peer is subscribed to result characteristics.

In this case, how could I achieve notifying it's updated value?

I've tried with `onSubscribe's updatedValueCallback`,
But It wasn't work.

It says, _updateValueCallback Is not function, but I've checked that I've initialized it successful.

this is my part of code.
```py
function CmdsDataChar() {
  bleno.Characteristic.call(this, {
    uuid: cmdsBase.DataUuid,
    properties: ['read', 'write']
  });
}

function CmdsResultChar() {
  this._updateValueCallback = null;
  bleno.Characteristic.call(this, {
    uuid: cmdsBase.ResultUuid,
    properties: ['read', 'notify']
  });
}

CmdsDataChar.prototype.onWriteRequest = function (data, offset, withoutResponse, callback) {
  CmdsResultChar._updateValueCallback(cmdsBase.ResultType.DATA);
  callback(this.RESULT_SUCCESS);
};

CmdsResultChar.prototype.onSubscribe = function (maxSize, updateValueCallback) {
  this._updateValueCallback = updateValueCallback;
};
```

**Comment by DanielTimLee** [comment]
My bad!

Solved it with setting updateValueCallback at outer Object.

**Comment by CBZakaria** [comment]
Can you show me the solution?
