### ISSUE TITLE
does bleno conducts Connection parameter Update when Central device is connected?

### ISSUE THREAD

**Issue by DanielTimLee** [sandeepmistry/bleno#304]
does bleno conducts Connection parameter Update when Central device is connected?

As in BLE connection sequence, just after connection is established those connection has to be updated with connection parameters such as `MIN_CONNECTION_INTERVAL` or `Supervisory Timeout`. 

but I can't find one in BLENO Library. Is there any place that conducts Connection parmeter update? (such as Bluez kernel layer?)

**Comment by sandeepmistry** [comment]
Short answer is no.
