### ISSUE TITLE
 Attempt to invoke virtual method 'java.util.List android.bluetooth.BluetoothGattService.getCharacteristics()

### ISSUE THREAD

**Issue by arizona2014** [sandeepmistry/bleno#307]
I'm trying to follow this tutorial -  https://www.snip2code.com/Snippet/667137/Cordova-BLE-Notify-Test-using-bleno-s-Te

So my confirguration is as follows : 
IONIC2 / BLE lib  for the frontend and
PI Zero W / NodeJS 6.10.3 / NPM 3.10.10

On PI I manage to get the test.js up and running and I can connect with the IONIC 2 app to it. 
On my IONIC2 after connection, I receive this from PI on my console : 

```
Object
  advertising: ArrayBuffer
  characteristics: Array[3]
   0: Object
        characteristic: "2a00"
        properties: Array[1]
           0: "Read"
           length: 1
           __proto__: Array[0]
        service:"1800"
        __proto__ : Object
   1: Object
        characteristic: "2a01"
        properties: Array[1]
           0: "Read"
           length: 1
           __proto__: Array[0]
        service: "1800"
        __proto__: Object
   2: Object
       characteristic: "34cd"
       properties: Array[2]
           0: "Read"
           1: "Write"
            length: 2
            __proto__: Array[0]
        service: "12ab"
        __proto__:Object
   length: 3
  id: "B8:27:EB:9C:36:E1"
  name:"raspberrypi"
  rssi:-61
  services: Array[3]
   0: "1800"
   1: "1801"
   2: "12ab"

```

In your tutorial you say we must interogate ffffffff-ffff-ffff-ffff-fffffffffff5 characteristic ... so on my code i have : 

```
this.ble.startNotification(this.device.id, 'ffffffff-ffff-ffff-ffff-fffffffffff0','ffffffff-ffff-ffff-ffff-fffffffffff5').subscribe(
      dataOK => {
        var data = new Uint32Array(dataOK);
        console.log(data);
      },
      dataKO => {
        console.log(dataKO);
      }
    );
```

On console I get this error : Attempt to invoke virtual method 'java.util.List android.bluetooth.BluetoothGattService.getCharacteristics()' on a null object reference , which is kind of normal since I see only 1800,1801, 12ab services.  

In the test.js file I see clearly fffffffffffffffffffffffffffffff0 and fffffffffffffffffffffffffffffff5 but when I run the code i get what i described above.

**Comment by arizona2014** [comment]
Couldn't let this error like that so I downloaded BLE Scanner on my android, discovered quickly my PI's ble connection and after connection, got for the first time same 3 services as my IONIC2 app.

Fortunatelly I've unpaired my test device and connected again, and voila ... this time I get the good characteristics : ffffffff-ffff-ffff-ffff-fffffffffff1, ffffffff-ffff-ffff-ffff-fffffffffff2 ... ffffffff-ffff-ffff-ffff-fffffffffff6

I subscribe on ffffffff-ffff-ffff-ffff-fffffffffff5 characteristic and by magic my nodejs app comes alive and starts incrementing each 5 seconds ... great news. So now I have to replicate this on my IONIC2 app. I now i connect successfully with test.js, also I know the nodejs does well its incrementing so i'm on the good path.

I have some questions though : 

* at this moment test.js accepts connections and sends notifications from/to any client. Is there a way to connect / send connection only to my IONIC2 app ? How can I implement that and where ?

* for the moment test.js sends only an integer value corresponding to a incremention. Can I send a file to my app ?

**Comment by sandeepmistry** [comment]
@arizona2014 

> at this moment test.js accepts connections and sends notifications from/to any client. Is there a way to connect / send connection only to my IONIC2 app ? How can I implement that and where ?

Nope

> or the moment test.js sends only an integer value corresponding to a incremention. Can I send a file to my app ?

You can only send up to a `maxValueSize` byte per notification.
