### ISSUE TITLE
UART equivalent

### ISSUE THREAD

**Issue by anweiss** [sandeepmistry/bleno#310]
I think I'm asking the right question, but is there a UART implementation equivalent to https://github.com/sandeepmistry/arduino-BLEPeripheral/tree/master/examples/serial in bleno? Would love to see this in the examples.

**Comment by sandeepmistry** [comment]
I'm not too keen on UART's over BLE in general, they generally don't leverage the benefits of GATT.

@anweiss What were you thinking the example would do? How do you think this would be beneficial to the community?

@jacobrosenthal any thoughts on this.

**Comment by anweiss** [comment]
So I ended up finding this -> https://github.com/xykox/nrfUART-echo which is what I was looking for.

**Comment by sandeepmistry** [comment]
@anweiss so can we close this?

**Comment by anweiss** [comment]
Fine by me. Thanks
