### ISSUE TITLE
Handoff of connection between Node processes

### ISSUE THREAD

**Issue by anweiss** [sandeepmistry/bleno#313]
Is there a way to perform a handoff of the Bluetooth connection between processes? Maybe by way of Unix sockets? Essentially looking to conduct a zero-downtime update, or as close to it as possible.

**Comment by sandeepmistry** [comment]
Hey @anweiss,

This is not really supported now, the HCI socket should persist in the fork and the connection handle for the incoming connection is global to the adapter. Recovery this afterwards would be a bit off the road ...
