### ISSUE TITLE
Dealing with short MTU

### ISSUE THREAD

**Issue by krishkal** [sandeepmistry/bleno#317]
I am not clear on how to handle a short MTU. On a R-Pi, the MTU seems to be 20. I am trying to send about 120 bytes of data, using the technique as shown in https://github.com/sandeepmistry/bleno/blob/master/test.js#L50-L75.

However, when the Read Characteristic is called, it is called only once with the offset 0. I would have expected it to be called multiple times with offsets of 0,21,41 etc.

What am I missing?

**Comment by sandeepmistry** [comment]
@krishkal you'll have to get you Android client to do a long read.
