### ISSUE TITLE
Emulate a HID device

### ISSUE THREAD

**Issue by neophob** [sandeepmistry/bleno#320]
Hi, thanks for this library

I try to run bleno to emulate a HID device. My BLE device is a realtek device, so the maxMtu is limited to 23 bytes.

the reportmap (2A4B) characteristic is about 60 bytes, this means a read requst must deliver multiple results - as i see multiple read requests with an increasing offset. my question: what should the callback look like, when the offset exceeds the data (aka end of data)?

just an empty RESULT_SUCCESS? currently I'm using this code:

```
HidCharacteristicReportMap.prototype.onReadRequest = function(offset, callback) {
  //max mtu = 23, this._gatt.maxMtu = 23;
  if (offset > this._value.length) {
    callback(this.RESULT_SUCCESS, Buffer.alloc(22));
  } else {
    const buffersize = Math.min(22, this._value.length-offset);
    const readValue = Buffer.alloc(buffersize);
    console.log('this._value.length',this._value.length, buffersize);
    this._value.copy(readValue, 0, offset, offset + buffersize);//, Math.min(offset+23, this._value.length-23));
    console.log(offset,'HidCharacteristicReportMap - onReadRequest: value =', readValue.toString('hex'));
    callback(this.RESULT_SUCCESS, readValue);
  }
};
```

**Comment by sandeepmistry** [comment]
@neophob please see: https://github.com/sandeepmistry/bleno/blob/master/test.js#L59-L75

**Comment by wind-rider** [comment]
@neophob did you succeed to emulate a HID device? Could you please show us how you did that?

**Comment by willwade** [comment]
@neophob - I'm with @wind-rider on this one. Even if you're not happy sharing code I Would love to know if you even succeeded. Thanks.
