### ISSUE TITLE
Measured power doesn't work on Raspberry pi

### ISSUE THREAD

**Issue by fafa92** [sandeepmistry/bleno#322]
I'm trying to turn my raspberry to an iBeacon with bleno but I cannot make it transmit with lower power, I've changed Tx(measured power)many times, when I use my BLE scanner I see that Tx power has changed but RSSI hasn't changed at all while with other beacon devices changing transmission power leads to a lower RSSI number. Has anyone had the same problem? @sandeepmistry

**Comment by sandeepmistry** [comment]
@fafa92 please see https://github.com/sandeepmistry/bleno/issues/125.
