### ISSUE TITLE
Increasing or decreasing Bluetooth Tx Power Level

### ISSUE THREAD

**Issue by suganshrestha** [sandeepmistry/bleno#323]
Hi Sandeep,

Is there a way that I can decrease or increase the transmission power level for the BLE system using the bleno library ?

Thanks

**Comment by sandeepmistry** [comment]
@suganshrestha please see https://github.com/sandeepmistry/bleno/issues/125.

**Comment by shotahino** [comment]
@sandeepmistry What is the default Tx power level in dBm?
