### ISSUE TITLE
Using both startAdvertising and startAdvertisingIBeacon

### ISSUE THREAD

**Issue by evaz1279** [sandeepmistry/bleno#327]
First off, I want to state that I love bleno! I'm using it on my raspberry pi3 and it was so easy to get going.

I have a use case where I want to advertise both an iBeacon and a service with a write characteristic. I then have an app on the phone that when the phone gets in close enough proximity it connects and writes a message to the write characteristic. 

It had been working perfectly until I tested this on a Samsung S6. I'm currently advertising theI recently ran into an issue when testing my app on Galaxy S6 where it would find the beacon, but could not connect to the pi. If I stop advertising the iBeacon then it can connect without issue. 

Simplified bleno code:
```
	if(state == 'poweredOn') {
		bleno.startAdvertising('echo', [serviceuuid]);

		bleno.startAdvertisingIBeacon(uuid, major, minor, measuredPower, function (error) {
			console.log('on -> advertisingIBeaconStart: ' + (error ? 'error ' + error : 'success'));
		});	
	}
	else {
		bleno.stopAdvertising();
	}
```
The reason why I'm posting this is because if I simply advertise the service and then use a shell script to advertise the iBeacon it works fine. Below is the main part of the shell script:
sudo /usr/bin/hcitool -i hci0 cmd 0x08 0x0008 1e 02 01 1a 1a ff 4c 00 02 15 $UUID $MAJOR $MINOR C5 00
sudo /bin/hciconfig hci0 leadv

I'd ideally like to advertise both the service and beacon through bleno without the use of the shell script. Any ideas why it is not working?

Thanks in advance!

**Comment by sandeepmistry** [comment]
@evaz1279 thanks for the positive feedback!

>I'd ideally like to advertise both the service and beacon through bleno without the use of the shell script. Any ideas why it is not working?

The last advertising call will most likely win. bleno isn't setup to do both, although you could use a timer to alternate ....
