### ISSUE TITLE
How to create Whitelist of Central devices on Peripheral 

### ISSUE THREAD

**Issue by skyn6t** [sandeepmistry/bleno#328]
Hi,

I recently started working on bleno and found it very much interesting and easy to use.
I have few challenges to achieve as mentioned in below scenarios.
Scenarios:
1. I need to create a list of central devices on peripheral who are suppose to connect to it (peripheral).
2. Based on role a central device should have permission to read or write to characteristic

How i can achieve these two scenarios?

**Comment by sandeepmistry** [comment]
@skyn6t this scenario is not supported.
