### ISSUE TITLE
Write data with Bleno

### ISSUE THREAD

**Issue by BlackWolf** [sandeepmistry/bleno#33]
Hi there,
I am currently trying to use Bleno to connect to an iOS 7 device. The connection works and the iOS device subscribes to my characteristic, but I don't really understand how to send data to the iOS device. The `onWriteRequest` handler is never called and there seems to be no `.write()` method or something similar on the characteristic, and I couldn't find anything in the documentation.

How exactly is this done?

**Comment by zach-luman** [comment]
@sandeepmistry @BlackWolf 
How did a notify characteristic work for data transfer from peripheral?
What I want is to implement broadcaster on my desktop app.(Electron app working on OS X)
My app starts BLE advertising using bleno but I'm not sure how to add advertisement -> manufacturerData.
