### ISSUE TITLE
Can't get echo example to advertise

### ISSUE THREAD

**Issue by kctoombs** [sandeepmistry/bleno#331]
Hi, 
I'm trying to run the echo example, but I can't seem to get it to advertise anything. Whenever I run the example, it prints "bleno - echo" to the terminal and nothing else. In the past I was able to get it to advertise, but I don't know what I'm doing differently now. Do you have any suggestions for getting it to advertise? 

Thank you

**Comment by sameeriitkgp** [comment]
Hey,
I've run into the same problem. How did you get past this?

Thanks.
