### ISSUE TITLE
any examples of handing >0 offset in `onReadRequest()`?

### ISSUE THREAD

**Issue by rynop** [sandeepmistry/bleno#335]
I'm struggling to find docs on how the `offset` param of `onReadRequest()` is populated, and what to do when it is > 0.

My guess is the data I'm returning is too long, seems if I return data that is < 100 bytes, I don't get a second call to `onReadRequest()`.

Below is some example code, In my `onReadRequest()` I'm reading data from my hardware which I then want to return back to the consumer of the peripheral.

On every `onReadRequest()` where the offset is `0` do I need to save it off, then when another call comes in that is > 0, I slice the buffer at the offset and return the sliced data?

How do you handle multiple consumers of your peripheral?  Or does bleno support one so you know the call with offset > 0 is a continuation of the same consumer?

```javascript
...
const forcePrecision = Math.pow(10, 3);
...

onReadRequest(offset, callback) {
    console.log('thing-data-characteristic::onReadRequest', offset);
    if (offset) {
      callback(this.RESULT_ATTR_NOT_LONG);
    } else {
      Promise.all([
          this._thing.getSpeed(),
          this._thing.getForce(),
        ])
        .then((responses) => {
          console.log(`Speed: ${responses[0]}`);
          console.log(`Force: ${responses[1]}`);
          console.log('---------------------------------');

          let data = new Buffer.allocUnsafe(4 * 8).fill(0);

          data.writeUInt8(supportedFlags, 0);  //GATT flags, tells functions this thing supports

          data.writeUInt8(responses[0], 1); //speed
          data.writeInt16LE(responses[0] * forcePrecision, 2, true); //force, 3 decimal precision

          callback(this.RESULT_SUCCESS, data);
        })
        .catch(err => {
          console.error('Error when reading thing data', err);
          callback(this.RESULT_UNLIKELY_ERROR);
        });
    }
  }
```
Are there any bleno code examples that show how to handle use cases where a read causes a > 0 offset?

Thanks in advance

**Comment by sandeepmistry** [comment]
@rynop please see: https://github.com/sandeepmistry/bleno/blob/master/test.js#L50-L75
