### ISSUE TITLE
[Raspberry Pi, Ubuntu Mate, systemd] Make bleno Node.js app start automatically and keep alive.

### ISSUE THREAD

**Issue by ImJCabus** [sandeepmistry/bleno#342]
I'm trying to auto start and keep alive my Node.js app featuring bleno.

However, I can't get it to work:

Info:
- Raspberry Pi 3
- Ubuntu Mate 15.04
- `node -v 8.6.0`
- `npm -v 5.3.0`

I created a service for `systemd` tool.
The service file is located at `/etc/systemd/system`.

![screen shot 2017-10-12 at 13 41 58](https://user-images.githubusercontent.com/6830248/31494331-25b31242-af53-11e7-89ab-218b9e823020.png)

The following is my Node entrance file `index.js`:

![screen shot 2017-10-12 at 13 43 18](https://user-images.githubusercontent.com/6830248/31494397-68ae7550-af53-11e7-817d-2360a0538f69.png)

I've activated the service using `sudo systemctl enable mx-ble-node`.

After `sudo reboot`, `systemctl status mx-ble-node` shows this:

![screen shot 2017-10-12 at 13 45 47](https://user-images.githubusercontent.com/6830248/31494463-aa46b9fa-af53-11e7-87ea-15bc64c268da.png)

Note that `bleno.state == powerdOff`.
bleno is not advertising. `onStateChange` is never called.

However, if I `sudo systemctl restart mx-ble-node`, and `systemctl status mx-ble-node` after that I get:

![screen shot 2017-10-12 at 13 47 12](https://user-images.githubusercontent.com/6830248/31494516-e59527ee-af53-11e7-94f4-e995c142e4bb.png)

Note that this time, `bleno.state == 'unknown'`.
`onStateChange` is called and the service is advertised correctly.

Things I've checked so far:
- Service is running (enabled)
- Executed `sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)`
- No difference if I start my service `After=` or `Before=` `bluetooth.target`.
- No difference if `bluetooth` service is enabled or disabled. (bleno README suggests disabling it)

Why isn't it working after boot, but after manual service restart?

**Comment by arget888** [comment]
Did you resolved the problem?

**Comment by ImJCabus** [comment]
Nope. Getting no answer at all to my question here kind of discouraged me...

**Comment by sandeepmistry** [comment]
Please see https://github.com/sandeepmistry/noble/issues/523#issuecomment-309094112

**Comment by charlieuniform** [comment]
Not sure if you got and answer but I tried this after reading the referenced threads. I added:
```
After=hciuart.service
```
to the service file. Also I have the bluetooth service disabled per bleno recommendation.

**Comment by stidiovip** [comment]
I have read all of this but I can't clearly se the working answere ?
HIs there any working solution for this ?

**Comment by virtuosonic** [comment]
Hi

I'm not sure if this is the best or at least correct way to do this, but it worked for me on Raspberry pi 3B+ running Raspbian stretch, here is my service file

```
[Unit]
Description=Sexbot bluetooth LE peripheral
After=sys-subsystem-bluetooth-devices-hci0.device
Wants=sys-subsystem-bluetooth-devices-hci0.device
Requires=sys-subsystem-bluetooth-devices-hci0.device
```

To find what dependency to add I used _**systemd-analize**_ to generate an startup order graph using the following command

`systemd-analyze plot > startup_order.svg`

Then opened with `xdg-open startup_order.svg`

**Comment by virtuosonic** [comment]
On raspbian-lite for some reason I don't understand, I had to delay more the start so the service file ended like this
```
[Unit]
Description=Sexbot bluetooth LE peripheral
After=multi-user.target
Requires=bluetooth.target
```
