### ISSUE TITLE
Workaround for Pi Zero W installation

### ISSUE THREAD

**Issue by akmandala** [sandeepmistry/bleno#348]
Hi, I've been manage to install the library on Pi Zero W, but to do so I need to do all pre-requisite (including updating node) on Pi Zero W, THEN do bleno installation on Pi 3, then bring back the sdcard to Pi Zero W. 
Anyone experiencing the same, and find a way to do full pi zero W install?

**Comment by keeslinp** [comment]
I was able to just run `npm i` for the rpi0w. What is the error that you're getting which prevents you from doing so?

**Comment by akmandala** [comment]
Sorry could not be more detail, but it just stuck for hours when I do sudo
npm install bleno, with or without -g., it is approximately 2/3 of progress
bar.

The environment is either latest stretch or jessie, both the same, after
doing apt-get update && upgrade, and also install latest node, then
following pre-requisite steps on this github readme.

**Comment by keeslinp** [comment]
I do remember that it took a few hours when I installed it, the pi0 isn't a very powerful device. What I ended up doing was cross-compiling when I created my image using yocto. That might not fit your use case though. I'd recommend just leaving it overnight just in case it is an issue of just being super slow.

Maybe try running it with `--verbose` to see if that gives more information?

**Comment by akmandala** [comment]
Ah yes, will do that and report back, need to build fresh one anyway.

**Comment by akmandala** [comment]
Sorry a bit a while on this, it is definitely work on Pi Zero W, but took much longer time, hours, compare to minutes if you do it on Pi 3. Given that A correct Node & NPM already installed on Pi Zero, I guess if someone want to save a bit of time, doing all installation on Pi 3 (if they have one).
