### ISSUE TITLE
Issue with more than four characteristics

### ISSUE THREAD

**Issue by Wardleth** [sandeepmistry/bleno#35]
Hi Sandeep,

I have an issue trying to simulate a peripheral with your tool. 
I coded a unique service with five characteristics with notify and write properties. From an Android app, I enable notifications for every characteristics and then I simulate modifications by sending 'write' commands and catching notifications.
The problem is that after a variable amount of commands sent, bleno does not send back the 'write response' as before (but still send the notification), so Android waits until a timeout disconnects the device. If I disable a characteristic, so I now have four of them instead of five, I get no issue and everything works fine...
Is there any limitations in the number of characterstics that a service can have ?

Wardleth

**Comment by sandeepmistry** [comment]
This should be fixed by 40497e8ef6cf3c386430f11b924fa441b7496119, there was some buffering issues with the stdin/stdout C/node.js pipe, the newline wasn't guarantee to be there after a single read call.
