### ISSUE TITLE
does not install cleanly

### ISSUE THREAD

**Issue by pstanton** [sandeepmistry/bleno#352]
I'm getting errors installing bleno, I'm not sure if they're fatal. the echo and batter examples run but i can't find the peripheral when i scan and there is no log message printed for 'stateChange' or 'advertisingStart' events.

> root@imx6ul-var-dart:~/bleno-battery-service# npm add bleno
> 
> > usb@1.2.0 install /root/bleno-battery-service/node_modules/usb
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp info it worked if it ends with ok
> node-pre-gyp verb cli [ '/root/node-v8.9.1-linux-armv7l/bin/node',
> node-pre-gyp verb cli   '/root/bleno-battery-service/node_modules/usb/node_modules/.bin/node-pre-gyp',
> node-pre-gyp verb cli   'install',
> node-pre-gyp verb cli   '--fallback-to-build' ]
> node-pre-gyp info using node-pre-gyp@0.6.30
> node-pre-gyp info using node@8.9.1 | linux | arm
> node-pre-gyp verb command install []
> node-pre-gyp info check checked for "/root/bleno-battery-service/node_modules/usb/src/binding/usb_bindings.node" (not found)
> node-pre-gyp http GET https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
> node-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
> node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@8.9.1 (node-v57 ABI) (falling back to source compile with node-gyp)
> node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v57-linux-arm.tar.gz
> node-pre-gyp verb command build [ 'rebuild' ]
> make: Entering directory '/root/bleno-battery-service/node_modules/usb/build'
>   CC(target) Release/obj.target/libusb/libusb/libusb/core.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/io.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
>   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
> ../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
>  #include <libudev.h>
>                      ^
> compilation terminated.
> libusb.target.mk:132: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
> make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
> make: Leaving directory '/root/bleno-battery-service/node_modules/usb/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/root/node-v8.9.1-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 4.1.15-224578-g05c9604-dirty
> gyp ERR! command "/root/node-v8.9.1-linux-armv7l/bin/node" "/root/node-v8.9.1-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/bleno-battery-service/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/root/bleno-battery-service/node_modules/usb/src/binding"
> gyp ERR! cwd /root/bleno-battery-service/node_modules/usb
> gyp ERR! node -v v8.9.1
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/root/node-v8.9.1-linux-armv7l/bin/node /root/node-v8.9.1-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/bleno-battery-service/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/root/bleno-battery-service/node_modules/usb/src/binding' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/bleno-battery-service/node_modules/usb/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> node-pre-gyp ERR! System Linux 4.1.15-224578-g05c9604-dirty
> node-pre-gyp ERR! command "/root/node-v8.9.1-linux-armv7l/bin/node" "/root/bleno-battery-service/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /root/bleno-battery-service/node_modules/usb
> node-pre-gyp ERR! node -v v8.9.1
> node-pre-gyp ERR! node-pre-gyp -v v0.6.30
> node-pre-gyp ERR! not ok
> Failed to execute '/root/node-v8.9.1-linux-armv7l/bin/node /root/node-v8.9.1-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/bleno-battery-service/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/root/bleno-battery-service/node_modules/usb/src/binding' (1)
> 
> > bluetooth-hci-socket@0.5.1 install /root/bleno-battery-service/node_modules/bluetooth-hci-socket
> > node-gyp rebuild
> 
> make: Entering directory '/root/bleno-battery-service/node_modules/bluetooth-hci-socket/build'
>   CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
> ../src/BluetoothHciSocket.cpp: In member function âvoid BluetoothHciSocket::emitErrnoError()â:
> ../src/BluetoothHciSocket.cpp:275:72: warning: âv8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) constâ is deprecated (declared at /root/.node-gyp/8.9.1/include/node/v8.h:3831): Use maybe version [-Wdeprecated-declarations]
>    Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
>                                                                         ^
>   SOLINK_MODULE(target) Release/obj.target/binding.node
>   COPY Release/binding.node
> make: Leaving directory '/root/bleno-battery-service/node_modules/bluetooth-hci-socket/build'
> npm WARN saveError ENOENT: no such file or directory, open '/root/bleno-battery-service/package.json'
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN enoent ENOENT: no such file or directory, open '/root/bleno-battery-service/package.json'
> npm WARN bleno-battery-service No description
> npm WARN bleno-battery-service No repository field.
> npm WARN bleno-battery-service No README data
> npm WARN bleno-battery-service No license field.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 (node_modules/usb):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> + bleno@0.4.2
> added 158 packages in 260.509s
>

**Comment by sandeepmistry** [comment]
Please see https://github.com/sandeepmistry/bleno#install and https://github.com/sandeepmistry/bleno#linux
