### ISSUE TITLE
compatibility with bluetooth-serial-port

### ISSUE THREAD

**Issue by farfromrefug** [sandeepmistry/bleno#353]
Hi

I am trying to make bleno work at the same time as ```bluetooth-serial-port```
The idea is to use ```bluetooth-serial-port``` to send big files when necessary.

My issue is that ```bleno``` needs ```bluetoothd``` to be stopped while ```bluetooth-serial-port``` needs it to be running.
On the main page you seem to mention that bleno could be working with ```bluetoothd``` but i don't see how.
In my case ```bleno``` starts correctly, advertising works but when i try nto connect nothing happens.

Can you help?

Thanks

**Comment by sandeepmistry** [comment]
Please see https://github.com/sandeepmistry/bleno/issues/24#issuecomment-142456475
