### ISSUE TITLE
macOS High Sierra: Echo example doesn't work

### ISSUE THREAD

**Issue by Y2JChamp** [sandeepmistry/bleno#358]
Hi,
i've followed the instructions to install and launch bleno, but when i start main.js of echo example it stucks at the following output "bleno - echo".
I'm running it on a MacBook Air with Sierra (ver. 10.13.1)

Any help is appreciated
Thanks

**Comment by Arvinwolf91** [comment]
Same problem using MacBook Air with Sierra 10.13.2. Were you able to fix it ?

**Comment by sandeepmistry** [comment]
@Y2JChamp @Arvinwolf91 please provide feedback on PR #360.

**Comment by sandeepmistry** [comment]
Closing this as a duplicate of https://github.com/sandeepmistry/bleno/issues/341.
