### ISSUE TITLE
Unique Identifier for connected iOS, Android devices.

### ISSUE THREAD

**Issue by ShaunFoo** [sandeepmistry/bleno#364]
Hi there, 

I'm new to raspberry pi, I'm currently working on an automated door lock system and I need a unique identifier for each connected devices. 

However the client address below

`bleno.on('accept', callback(clientAddress)); // not available on OS X 10.9
 `

is giving me different device addresses overtime for a device, this is meant to be a security measure but it doesn't help me in my case. 

Any way for me to achieve this? Thank you in advance.

**Comment by sandeepmistry** [comment]
This is not supported, iOS is for sure rotating Bluetooth addresses.
