### ISSUE TITLE
How can I change the TX address 

### ISSUE THREAD

**Issue by bluetiger30** [sandeepmistry/bleno#366]
Hi, 
how can I change the TX address? 
I noticed that there is address change event in the bleno file which listens to the address of the BLE device, is there a way to possibly be able to change that address?

I'm using the following BLE module if that helps :
https://www.asus.com/uk/Networking/USBBT400/
if its easier to change the TX address of the BLE module on a raspberry pi 3 then I would love to do that?

**Comment by nemr-maher** [comment]
alternativly , when I set the foloowing in the hci.js file :
`cmd.writeUInt8(0x01, 9); // own addr typ
`
it changed the TX address to 00000000 , can I change that to something either than 00000000?

**Comment by bluetiger30** [comment]
alternativly , when I set the foloowing in the hci.js file :
`cmd.writeUInt8(0x01, 9); // own addr typ
`it changed the TX address to 00000000 , how can I change that to something other than 00000000?

**Comment by sandeepmistry** [comment]
This is not supported by this library.
