### ISSUE TITLE
How to start advertise on Raspberry Pi Reboot/startup

### ISSUE THREAD

**Issue by ShaunFoo** [sandeepmistry/bleno#371]
Hello, I'm working on a project which involves unlocking a gate from a mobile app with bluetooth.

I'm using this library to create the bluetooth services and it's working great but I have no idea how to start advertisement if the raspberry pi reboots or if the bleno app crash.

Any tips would be appreciated.

**Comment by Uniphix** [comment]
Hi @ShaunFoo I use a combination of a few tools to help with that.

First of all I use PM2 to help monitor, have startup rules for our applications to come online.  It will also take care of any application crashes and reboot them automatically.

http://pm2.keymetrics.io/

Ben

**Comment by ShaunFoo** [comment]
Hey Thanks for the tip @Uniphix !

I actually already got it to work with another similar tool [forever](https://github.com/foreverjs/forever).

After installing this, I added a crontab command
`@reboot sudo forever start path/to/ble.js`

Now it's working perfectly as I intended.
