### ISSUE TITLE
bleno and noble

### ISSUE THREAD

**Issue by fvisticot** [sandeepmistry/bleno#373]
It's no clear for me if it is possible to use bleno an noble in the SAME TIME
- Advertising a iBeacon message with bleno
AND in the SAME TIME
- Scanning for BLE device around the device with noble

If not possible is there a workarround ? start / stop advertising to allow scanning by example ?

**Comment by sandeepmistry** [comment]
Should be possible with multiple Bluetooth (USB) adapters and setting env vars as per the read me.
