### ISSUE TITLE
Enhance: Allow adjusting connection latency

### ISSUE THREAD

**Issue by janrueth** [sandeepmistry/bleno#38]
On iOS, there is the possibility for a peripheral to change the connection latency, i.e. the inter packet interval, which basically limits the possible datarate. This API exists on OS X too (however, it is broken as far as I can tell). The API allows three different latencies.

On Linux this can be done using `hcitool lecup`, which upgrades the connection to more specific values. For testing purposes (my project requires initial fast data rates) I added the following to `l2cap-ble.c` in `src/`: (the parameters match the parameters of `hcitool lecup`)

``` cpp
void hci_le_conn_update2(int dd, uint16_t handle, uint16_t min, uint16_t max,
                        uint16_t latency, uint16_t to_multiplier)
{
        le_connection_update_cp cp;
    struct hci_request rq;
    evt_le_connection_update_complete evt;

        memset(&cp, 0, sizeof(cp));

        cp.handle               = htobs(handle);
        cp.min_interval    = htobs(min);
        cp.max_interval    = htobs(max);
        cp.latency         = htobs(latency);
        cp.supervision_timeout  = htobs(to_multiplier);
        cp.min_ce_length           = htobs(0x0001);
        cp.max_ce_length           = htobs(0x0001);


    memset(&rq, 0, sizeof(rq));
    rq.ogf = OGF_LE_CTL;
    rq.ocf = OCF_LE_CONN_UPDATE;
    rq.cparam = &cp;
    rq.clen = LE_CONN_UPDATE_CP_SIZE;
    rq.event = EVT_LE_CONN_UPDATE_COMPLETE;
    rq.rparam = &evt;
    rq.rlen = sizeof(evt);

    if(hci_send_req(dd, &rq, 1000) < 0) {
        // printing to console seems a bad idea as it seems to be used for communication
        // if we land here, BAAAD
             //return -1;
    }

    if(evt.status) {
          // baaaad
         // return -1;
    }
    // return 0;  GOOD
}
```

For testing purposes and because I haven't got the time to understand how the js part communicates with the c part, I added the following in the main function after a successful connection accept: (Please note, I only added the one function call before the while loop)

``` cpp
...
  baswap(&clientBdAddr, &sockAddr.l2_bdaddr);
      printf("accept %s\n", batostr(&clientBdAddr));

      l2capConnInfoLen = sizeof(l2capConnInfo);
      getsockopt(clientL2capSock, SOL_L2CAP, L2CAP_CONNINFO, &l2capConnInfo, &l2capConnInfoLen);
      hciHandle = l2capConnInfo.hci_handle;

      // force faster connection
      // This should be compatible with iOS requirements for LowLatency
      hci_le_conn_update2(hciSocket, hciHandle, 20, 40, 0, 5000);
      while(1) {
        FD_ZERO(&rfds);
        FD_SET(0, &rfds);
...
```

I haven't really got the time to test it, I will do later today. It would be cool if bleno would export this functionality to the top level to allow switching the latency depending on the state the peripheral is in. As OS X Corebluetooth API allows similar latency adjustments I would allow to be as specific as the linux API is to the top level of bleno and match it to the closest setting Corebluetooth offers. I think this would allow the biggest flexibility while offering only a single interface and as the latency changes are not guaranteed it is fine to adjust them on OS X to the closest possible one.

**Comment by SandyChapman** [comment]
Hey guys, I know this is an old thread but I was pointed to this thread from a comment on my StackOverflow answer here:

http://stackoverflow.com/a/21678727/1270148

Not sure if this is useful to you or not, but I was able to modify hci.c to allow sending connection update requests from a Linux BLE peripheral using bluez 5.14.

Patch:
https://gist.github.com/SandyChapman/4a64c9ea22cd27d935e3

There's quite a bit of background on my SO answer and some additional details in my messages on the bluez mailing list from that time:

http://marc.info/?l=linux-bluetooth&m=139203542730183&w=2

**Comment by neyric** [comment]
Hey guys,

I confirm that @SandyChapman 's patch works, and is usable from user space (no need for a kernel module...).
I've just dumped his patch in hci-ble.c to test it without recompiling BlueZ, and it works just fine : 
https://github.com/neyric/bleno/commit/97d8ed3fe6345a33e8ebf4eb0006e03b751bdde6

Now a still pending issue is that a first con_update request is sent by the slave right after the connection, with different connection parameters not controlled by us... But I'm still unable to find where in BlueZ...

**Comment by sandeepmistry** [comment]
@SandyChapman @neyric I've been working on using raw HCI sockets on Linux in the following branch: https://github.com/sandeepmistry/bleno/tree/bluetooth-hci-socket

Once it's merged to master, it should be pretty straightforward to have an API or mechanism on Linux to set the connection parameters after a connection is established.

**Comment by neyric** [comment]
@sandeepmistry :+1: 
I had seen the node-bluetooth-hci-socket project, which looked very promising, but the implementation in Bleno looked difficult, so this branch is pure miracle for me :) Thank you so much !

I've tried this morning, but it looks like there is a mixup in the Gatt discovery... (the battery service is not working, and if I add another service, it appears, but within the second profile...)
Almost there !

**Comment by orenku** [comment]
Hi @sandeepmistry,

Following up the above issue since I'm facing the exact issue - I have a constraint on connection interval value. I looked for how to set CONN_PARAM_UPDATE_REQUEST in order to control connection interval from within bleno project.

Using debug messages I noticed that Hci.prototype.processLeConnUpdateComplete() (from hci.js) is called, hence I assume that connection update parameter request is issued somewhere internally.

Can you point out where/how it is being called and how can I control its parameters.

**Comment by sandeepmistry** [comment]
Hi @orenku,

> Using debug messages I noticed that Hci.prototype.processLeConnUpdateComplete() (from hci.js) is called, hence I assume that connection update parameter request is issued somewhere internally.

Maybe the central or Linux kernel is changing them? HCI dump capture will provide more details on this.

There is nothing in bleno to trigger this action currently.
