### ISSUE TITLE
Example echo disconnects with error 22

### ISSUE THREAD

**Issue by Domvel** [sandeepmistry/bleno#383]
The example "Echo" on Raspberry PI with bleno 0.5.0 disconnects after about 30 seconds with `Error 22 GATT CONN TERMINATE LOCAL HOST`. And no services / characteristics are visible (discovered). 
Is this a known issue?

**Comment by don** [comment]
I'd try disabling `bluetoothd`, it can cause problems with services not showing up. 

    sudo service bluetooth stop

Then manually start the bluetooth

    sudo hciconfig hci0 up

If the disconnect keeps happening, run btmon to get detailed log of the communication

    sudo btmon

If you're still not seeing all the services, apps like nRF Connect have an "Refresh Services" option which should overwrite any cached data.

I was not able to duplicate this on a Raspberry Pi 3 B+. An iPhone 7 (11.3.1) and Nexus 5X (8.1.0) stayed connected.

**Comment by don** [comment]
@Domvel is this still an issue?

**Comment by Domvel** [comment]
Not more followed.
