### ISSUE TITLE
Device name doesn't work properly (at least in Ubuntu)

### ISSUE THREAD

**Issue by SynerG** [sandeepmistry/bleno#43]
I'm using this great library in Ubuntu 12.04. I don't know if this is an issue in Ubuntu or Bleno, but here I go:

The name specified using Bleno seems to be used only in the advertisement, but it is not the name provided bythe  0x1800 primary service. The service replies 'ubuntu' as the name.

More specifically:
If I define the name 'myName' using:
bleno.startAdvertising('myName', ['fff0']);
I get the next result:
- In LightBlue (iOS):
   - It detects a peripheral showing the name 'ubuntu', although in a small typography it also indicates 'myName'. I guess the small typography shows the contents of the advertisement, but LightBlue considers the name to be ubuntu.

- In nRF Master (Android)
   - It shows 'myName' as the name before connecting.
   - However, if I request the value of the characteristic 0x2A00 (Device Name) in the primary service 0x1800, I get the value 'ubuntu'.

Considering these observations, it seems that ubuntu adds its own 0x1800 primary service to my peripheral.
I have tried to overwrite this service defining my own 0x1800 primary service, with my own 0x2A00 (Device Name) and 0x2A01 (Appearance) characteristics. However, it doesn't work. nRF Master detects two 0x1800 services, the 'ubuntu' service is still there.

Do you think this could be a bug in Bleno? or Ubuntu will always define its own name characteristic?

**Comment by sandeepmistry** [comment]
@SynerG a791a99 addresses this ...

**Comment by SynerG** [comment]
Great @sandeepmistry, I see you have finally solved it using an environment variable. Thank you
