### ISSUE TITLE
Device directly starts with 'poweredOff' state

### ISSUE THREAD

**Issue by SynerG** [sandeepmistry/bleno#45]
At executing any .js, the first event received is 'stateChange' to 'poweredOff'. The change to 'poweredOn' is never received. Therefore, the peripheral never starts the advertisement.

I guess there is some problem with the platform. I am testing noble in a Raspberry Pi (xbian):
Kernel: 3.12.7+
bluez_4.99-2
node v0.10.26
I have tried with an app that is working properly in Ubuntu and with the tests in bleno (test.js and test-ibeacon.js). The three files work in Ubuntu, but doesn't work in my Rpi.
In all the cases, 'stateChange' to 'poweredOff' is the only event received.

Note: I have checked and the patch proposed in Issue #18 is already applied to my version of bleno.

**Comment by miparnisari** [comment]
I have this same issue on Windows (device is poweredOff) on start. Any ideas how to fix it?

**Comment by sandeepmistry** [comment]
@miparnisari please open a new issue with debug logs `set DEBUG=*` and the code you are using. It might be related to https://github.com/sandeepmistry/node-bluetooth-hci-socket/issues/30.
