### ISSUE TITLE
BLE_NODE_CONFIGURATION

### ISSUE THREAD

**Issue by akycdi** [sandeepmistry/bleno#479]
Hi,

I am new to this ble devices can anyone help me to set up the node on pi. I Have tried setting up with the latest version and latest stable versions of npm.  
Can anyone mention which npm and nodejs version to be used in Raspberrypi.

**Comment by rzr** [comment]
May I suggest to try @abandonware fork and report at:
Relate-to: https://github.com/abandonware/bleno/issues/17

**Comment by akycdi** [comment]
Thanks for you reply!.. Just changed the version it fixed everything back then
