### ISSUE TITLE
Indicate Support for Linux

### ISSUE THREAD

**Issue by mikeholler** [sandeepmistry/bleno#58]
I'm curious when support for the `indicate` property is scheduled for Linux. I have an application that requires this functionality so I was reading through the source code to see how to make it work. `indicate` is implemented on Mac already, and as far I can tell the following code block is all that was needed to make `indicate` work on OS X:

```js
if (characteristic.properties.indexOf('indicate') !== -1) {
    if (characteristic.secure.indexOf('indicate') !== -1) {
        properties |= 0x200;
    } else {
        properties |= 0x20;
    }
}
```

When browsing through the Linux code, I found this block that looks very similar to the one above:

```js
 if (characteristic.properties.indexOf('notify') !== -1) {
    properties |= 0x10;

    if (characteristic.secure.indexOf('notify') !== -1) {
        secure |= 0x10;
    }
}
```

If I added the following to `l2cap-ble.js`, is this all that is necessary to support Linux?

```js
 if (characteristic.properties.indexOf('indicate') !== -1) {
    properties |= 0x200;

    if (characteristic.secure.indexOf('indicate') !== -1) {
        secure |= 0x20;
    }
}
```

And of course, there is always the possibility `indicate` support is already on the way. Does anybody know anything about this? I really could use it for some projects I'm working on.

If there is more to do, what is it? I could find few mentions of the word `indicate` in the repository, so I would guess that this would provide support, but I am very new to both Node and BLE and am not versed enough to know for sure. Thanks for taking the time to read this.

**Comment by rowanc** [comment]
@sandeepmistry, thanks for this awesome lib.  I need indicate support in linux, and am m happy to submit a pull request.  Is there anything else that I should be looking at than what you listed above?  I've worked with BLE minimally.

**Comment by sandeepmistry** [comment]
@rowanc that would be sweet!

It would be great to make sure the behaviour is the same as OS X. We'll need to confirm the characteristic ```onNotify``` method is called when a ```ATT_OP_HANDLE_CNF``` message is received. If OS X doesn't call it now, maybe we should introduce a new ```onIndicate``` method?

**Comment by sandeepmistry** [comment]
https://github.com/sandeepmistry/bleno/commit/732d83adacc7bf265642c1cd35e37262a09773b1 adds support for this!
