### ISSUE TITLE
Write attribute that is more than 20 bytes?

### ISSUE THREAD

**Issue by dzungductran** [sandeepmistry/bleno#59]
Is there a way to write more than 20 bytes? I have my iOS LightBlue application tries to write to my BLE peripheral that run on my Linux box, it seems to only take 20 bytes. Is there a way to write more than 20 bytes?

**Comment by carlonluca** [comment]
According to the answer here https://devzone.nordicsemi.com/question/34572/ble-long-write, Android should be able to handle long writes already. I tested it and it seems to work on Nordic devices. However it does not seem to properly work with bleno. Maybe something is still missing implementation in bleno? I solved by changing MTU but the "incompatibility" remains.

**Comment by andrea-spotsoftware** [comment]
Ciao @carlonluca, 
I had the same problem. The only workaround that I've found to send a buffer > 20 bytes is to use two separate characteristics. One is for sending 20 bytes chunks, the other one is for sending the last chunk. The sender has the responsibility to split the buffer in chunks of 20 bytes, while bleno have to fill a buffer appending every chunk received on the first characteristic, and closing the buffer when it receives a write on the second characteristic.
Hope it helps.

**Comment by ge0rg** [comment]
We were able to successfully write up to 512 bytes from Android using the code from #77 on a Linux peripheral.

**Comment by carlonluca** [comment]
Thanks, but the problem is not doing it. I'm already writing more than 20 bytes and it works properly. Changing MTU is sufficient. The point here is that bleno is not "compatible" with other peripherals. It may be good to implement what is missing, assuming of course something is really missing, which I am not sure.

**Comment by carlonluca** [comment]
@ge0rg That seems exactly what is needed. I created a fork including that change and it seems to work perfectly so far. I'd include that in the repo, it is useful.

**Comment by sandeepmistry** [comment]
@andrea-spotsoftware @ge0rg @carlonluca #112 is currently tracking this, please follow it for progress. Prepare and execute write commands are currently not implemented on the Linux side of bleno.

#77 works for Linux, but does not include support for OS X, that is the reason why is hasn't been merged in.
