### ISSUE TITLE
Set Advertisement Frequency

### ISSUE THREAD

**Issue by pfafman** [sandeepmistry/bleno#60]
Is it possible to add the ability to adjust the advertisement frequency.  I think on Linux it defaults to 1Hz and in a BLE rich environment the advert package might not get detected for a few cycles.  

When doing iBeacons this leads on iOS devices for them listing them as proximity unknown and not picking up the iBeacon in a timely fashion.

This is possible if using the hcitool, although not really intuitive.  [See this question](http://stackoverflow.com/questions/21124993/is-there-a-way-to-increase-ble-advertisement-frequency-in-bluez)

Thanks,
Tim

**Comment by sandeepmistry** [comment]
The advertising interval can now be set on Linux via the ```BLENO_ADVERTISING_INTERVAL``` enviroment variable.

More info. here:
https://github.com/sandeepmistry/bleno#set-advertising-interval
