### ISSUE TITLE
Handling more than one connected device to peripheral

### ISSUE THREAD

**Issue by dragom** [sandeepmistry/bleno#7]
It looks that there should be new process l2cap-ble to handle new accept when all other are connected? 
https://github.com/sandeepmistry/bleno/blob/master/src/l2cap-ble.c#L78

I tested with one ble periphereal (bleno) and two ble's as central modules (noble) that connects and try to read characteristics. Really not know ble specs. Maybe this is normal behavior?

**Comment by MeMyselfI** [comment]
Is there any update to it now?

**Comment by sandeepmistry** [comment]
@MeMyselfI no progress on this since last comment.
