### ISSUE TITLE
bleno disconnects when smartphone access a secure charactheristic

### ISSUE THREAD

**Issue by andrea-spotsoftware** [sandeepmistry/bleno#71]
Hi everyone,
thank you for your great job!
I'm doing some tests with bleno installed on a Raspberry Pi, and i'm experiencing big issues with secure characteristics.

I can replicate this scenario with LightBlue on iPhone 5, and with nRFControlPanel on google nexus 5.

If i define a service with a secure charachteristic, and i try to read this charachteristic, bleno fires the disconnect callback, and it freezes until i restart it.

I've already downgraded to bluez 4.101, nothing changed.

**Comment by corzand** [comment]
Hello @sandeepmistry 
I'm here again to say that installing by apt-get bluetooth and bluez-utils don't solve the disconnect problem. 
The only trick that I found to work with secure characteristics (that requires bonding) is to follow these instructions:

Install blueZ 4.101 from sources:
```sh
sudo apt-get install libdbus-glib-1-dev
sudo apt-get install libexpat1-dev
wget http://www.kernel.org/pub/linux/bluetooth/bluez-4.101.tar.xz
tar -xvf bluez-4.101.tar.xz
cd bluez-4.101
./configure 
sudo make
sudo make install
```

    sudo nano /etc/init.d/bluetoothd

```sh
#! /bin/sh
### BEGIN INIT INFO
# Provides:          
# Required-Start:    $all
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manages the bluetoothd daemon
# Description:       Manages the bluetoothd daemon
### END INIT INFO

# Author:Andrea Corzani <>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

HCI=/usr/local/sbin/hciconfig
BLUETOOTH=/usr/local/sbin/bluetoothd
BLUE_PID=/var/run/bluetoothd.pid
BLUE_FILE="/var/log/bluetoothd.log"

PID=

BLUETOOTH_ENABLE=true

case "$1" in
start)
   if [ "$BLUETOOTH_ENABLE" = "true" ]; then
       #echo "Bringing up Bluetooth LE dongle"
       #$HCI hci0 up
       echo -n "Start bluetoothd... "
       $BLUETOOTH >> $BLUE_FILE 2>&1 &
       PID=$!
       echo "pid is $PID"
       echo $PID >> $BLUE_PID
    fi

    ;;
stop)

   if [ -e $BLUE_PID ]; then
       echo -n "Stop Bluetooth..."
       echo -n "killing "
       echo `cat $BLUE_PID`
       kill `cat $BLUE_PID`
       rm $BLUE_PID
   fi
   ;;
restart)
   $0 stop
   $0 start
        ;;
*)   echo "Usage: $0 (start|stop)"
        exit 1
        ;;
esac
exit 0
```

    sudo chmod uog+rx /etc/init.d/bluetoothd
    sudo update-rc.d bluetoothd defaults

Tested in raspberry pi and raspberry pi 2.

**Comment by sandeepmistry** [comment]
@corzand was ```bluetoothd``` running after you installed ```bluetooth bluez-utils```?

**Comment by TheClownDE** [comment]
Hi,
I'm facing the same issue and tried all the above solutions.
Currently I am working withe BlueZ 5.41 (via Homepage), node v4.5.0 and noble/bleno v1.6.
I am able to read and write to my on application (peripheral on Linux Mint 17.2) with my smartphone (Android, nRF Connect app) but as soon as I add the "secure" filed in the characteristic the devices disconnect on write/read request.
The also disconnect on bonding.
Any Solutions?

Thanks for any help,
TheClown

**Comment by ghost** [comment]
> Hey!
> Good news: after some hours of time spent trying to reproduce problems, i found out how to do to let bleno work!
> i have bluez 4.101 installed.
> these are the steps:
> 
> turn on raspberry pi
> $ sudo bluetoothd stop
> $ sudo hciconfig hci0 up
> $ sudo node bleno_tests/test.js
> 
> In this way, bleno secure (read) characteristic works, with iOs or Android
> The last question is: why? :)

Hi Andrea, I am using the python version of bleno, and I also let secure read work when the notification is on, bluetoothd start from the start up. 
But I cannot let secure write work, did you get secure write work?

**Comment by andrea-spotsoftware** [comment]
@AndyChoon if I can remember, I had to switch secure characteristics into non-secure, to work without problems. 
It was 5 years ago, then I havn't had any other experience with bleno.
Sorry :\

**Comment by ghost** [comment]
> @AndyChoon if I can remember, I had to switch secure characteristics into non-secure, to work without problems.
> It was 5 years ago, then I havn't had any other experience with bleno.
> Sorry :\

Thank you. So the secure write is impossible with bleno now. I am quite new to enter into this field. I am developing some BLE application for a stand-alone device, so that is why I have to build security on write. Hope others able to figure it out. :)
