### ISSUE TITLE
Guidance on TypeError / Buffer and returning string data from a custom characteristic

### ISSUE THREAD

**Issue by rexstjohn** [sandeepmistry/bleno#86]
Hello, I am having a lot of fun with Bleno thanks for creating it. I am really excited about the possibilities with Intel Edison and have been working on a BLE service for everyone to use (https://github.com/rexstjohn/edison-ble). 

I having issues with Buffers (probably due to a misunderstanding as to how to prepare data for BLE). In this case,  I am trying to return a human readable hard disk storage space value from Edison. What is the proper way to return a piece of information like "220.23M?" I have tried a number of things with no success.

Example:

 var EdisonStorageSpaceCharacteristic = function() {
  EdisonStorageSpaceCharacteristic.super_.call(this, {
      uuid: 'e602af1e-b2f2-46cb-beff-364d5d96eb76',
      properties: ['read'],
      descriptors: [
        new Descriptor({
            uuid: '2901',
            value: 'Available hard disk space'
        })
      ]
  });
};

util.inherits(EdisonStorageSpaceCharacteristic, Characteristic);

EdisonStorageSpaceCharacteristic.prototype.onReadRequest = function(offset, callback) {
    // Fetch free space in M, I know this to work properly but I get the buffer error
    exec('df -h | grep /dev/root | awk \'{ print $4; }\'', function (error, stdout, stderr) {
      var data = stdout.toString().replace(/(\r\n|\n|\r)/gm,"");
      data = parseInt(data.substring(0, data.length - 3));
      console.log("available storage: " + data);
      callback(this.RESULT_SUCCESS, data);
    });
};

And I am getting:

buffer.js:784
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:784:11)
    at Buffer.writeUInt8 (buffer.js:794:5)
    at L2capBle.errorResponse (/node_app_slot/node_modules/bleno/lib/linux/l2cap-ble.js:314:7)
    at null.<anonymous> (/node_app_slot/node_modules/bleno/lib/linux/l2cap-ble.js:716:35)
    at /node_app_slot/edison-wifi-status-characteristic.js:40:7
    at ChildProcess.exithandler (child_process.js:645:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)

**Comment by ldmohan** [comment]
Hello Sandep,
I need to read some values from a txt file  and send to the central. I just modified battery-level-characteristic file as follows.

BatteryLevelCharacteristic.prototype.onReadRequest = function(offset, callback) {

 
    exec('tail -1 test.txt', function (error, stdout, stderr) {

      	var data = stdout.toString().replace(/(\r\n|\n|\r)/gm,"");
	data = parseInt(data);
	console.log ("last value "+data);
	callback(this.RESULT_SUCCESS, new Buffer(data));
    });

};
module.exports = BatteryLevelCharacteristic;

but when i try to read from central i got an error ... 

 on -> stateChange: poweredOn
on -> advertisingStart: success
last value 50

buffer.js:705
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt8 (buffer.js:715:5)
    at L2capBle.errorResponse (/home/pi/node_modules/bleno/lib/linux/l2cap-ble.js:314:7)
    at null.<anonymous> (/home/pi/node_modules/bleno/lib/linux/l2cap-ble.js:716:35)
    at /home/pi/node_modules/bleno/examples/battery-service/battery-level-characteristic.js:36:2
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)

Any help please

**Comment by sandeepmistry** [comment]
@ldmohan please see my first reply.

You are using the ``Buffer`` API incorrectly.

``` javascript
exec('tail -1 test.txt', function (error, stdout, stderr) {
    var data = stdout.toString().replace(/(\r\n|\n|\r)/gm,"");
    data = parseInt(data);
   console.log ("last value "+data);
   
   var buffer = new Buffer(4); // arg to Buffer is size in bytes
   buffer.writeUInt32LE(data, 0); // fill in bytes

   callback(this.RESULT_SUCCESS, buffer);
});
```

**Comment by ldmohan** [comment]
Hello Sandeep, Unfortunately the same error has occurred even for the hardcode value.


BatteryLevelCharacteristic.prototype.onReadRequest = function(offset, callback) {

 
    exec('tail -1 test.txt', function (error, stdout, stderr) {
   /* var data = stdout.toString().replace(/(\r\n|\n|\r)/gm,"");
    data = parseInt(data);
    console.log ("last value "+data);
    var buffer = new Buffer(4); // arg to Buffer is size in bytes
    buffer.writeUInt32LE(data, 0); // fill in bytes*/

   callback(this.RESULT_SUCCESS, new Buffer([98]));
});

};
module.exports = BatteryLevelCharacteristic;


throws error...........


on -> stateChange: poweredOn
on -> advertisingStart: success

buffer.js:705
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt8 (buffer.js:715:5)
    at L2capBle.errorResponse (/home/pi/node_modules/bleno/lib/linux/l2cap-ble.js:314:7)
    at null.<anonymous> (/home/pi/node_modules/bleno/lib/linux/l2cap-ble.js:716:35)
    at /home/pi/node_modules/bleno/examples/battery-service/battery-level-characteristic.js:38:4
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)

Thanks 
Mohan

**Comment by ldmohan** [comment]
Hello Sandeep, Unfortunately the same error has occurred even for the hardcode value.

BatteryLevelCharacteristic.prototype.onReadRequest = function(offset, callback) {exec('tail -1 test.txt', function (error, stdout, stderr) {
/* var data = stdout.toString().replace(/(\r\n|\n|\r)/gm,"");
 data = parseInt(data);
 console.log ("last value "+data);
 var buffer = new Buffer(4); // arg to Buffer is size in bytes
 buffer.writeUInt32LE(data, 0); // fill in bytes*/
callback(this.RESULT_SUCCESS, new Buffer([98]));
 });};
 module.exports = BatteryLevelCharacteristic;
throws error...........

on -> stateChange: poweredOn
 on -> advertisingStart: successbuffer.js:705
 throw TypeError('value is out of bounds');
 ^
 TypeError: value is out of bounds
 at TypeError ()
 at checkInt (buffer.js:705:11)
 at Buffer.writeUInt8 (buffer.js:715:5)
 at L2capBle.errorResponse (/home/pi/node_modules/bleno/lib/linux/l2cap-ble.js:314:7)
 at null. (/home/pi/node_modules/bleno/lib/linux/l2cap-ble.js:716:35)
 at /home/pi/node_modules/bleno/examples/battery-service/battery-level-characteristic.js:38:4
 at ChildProcess.exithandler (child_process.js:646:7)
 at ChildProcess.emit (events.js:98:17)
 at maybeClose (child_process.js:756:16)
 at Socket. (child_process.js:969:11)
Actually what I want is just read a value from a file and send it to the master device. Here I use two RPi and CSR dongle for both central and peripheral devices. 
Thanks 
 Mohan

**Comment by sandeepmistry** [comment]
Hmm, @ldmohan it might actually be related to the value of ``this``, try out:

```javascript
exec('tail -1 test.txt', function (error, stdout, stderr) {
    var data = stdout.toString().replace(/(\r\n|\n|\r)/gm,"");
    data = parseInt(data);
   console.log ("last value "+data);

   var buffer = new Buffer(4); // arg to Buffer is size in bytes
   buffer.writeUInt32LE(data, 0); // fill in bytes

   callback(this.RESULT_SUCCESS, buffer);
}.bind(this));
```

or


```javascript
exec('tail -1 test.txt', function (error, stdout, stderr) {
    var data = stdout.toString().replace(/(\r\n|\n|\r)/gm,"");
    data = parseInt(data);
   console.log ("last value "+data);

   var buffer = new Buffer(4); // arg to Buffer is size in bytes
   buffer.writeUInt32LE(data, 0); // fill in bytes

   callback(Characteristic.RESULT_SUCCESS, buffer);
});
```

**Comment by ldmohan** [comment]
Thanks Sandeep!"callback(Characteristic.RESULT_SUCCESS, buffer);"is working
