### ISSUE TITLE
Installing Bleno on Edison fails

### ISSUE THREAD

**Issue by danki** [sandeepmistry/bleno#96]
Had to re-install everything on my Intel edison but now for some reason im not able to install bleno at all:

![screen shot 2015-02-16 at 11 18 55 pm](https://cloud.githubusercontent.com/assets/2181315/6220101/3c68c274-b632-11e4-8098-f3496122b18a.png)

I have tested everything, reinstalling Edison multiple times, re-configuring it but it just dont work any more.

**Comment by sandeepmistry** [comment]
It's buried in the screenshot, but have you looked at:
![bleno 96](https://cloud.githubusercontent.com/assets/1163840/6220323/0966ddcc-b603-11e4-98bf-12fa27ac3023.png)

https://github.com/sandeepmistry/noble#prerequisites

**Comment by danki** [comment]
That was it, thank you ! 
Sorry for that, i thought i had installed bluez, thats why i was confused :)

**Comment by sandeepmistry** [comment]
No worries, glad that helped ...
